In [1]:
from bs4 import BeautifulSoup
import requests
url = BeautifulSoup('https://www.worldometers.info/coronavirus/', 'html.parser')
response = requests.get(url)
response

C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:417: MarkupResemblesLocatorWarning: "https://www.worldometers.info/coronavirus/" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  warnings.warn(

In [2]:
soup =response.text
soup = BeautifulSoup(soup,"lxml")
soup

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]--><!--[if IE 9]> <html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Coronavirus Update (Live): 116,216,580 Cases and 2,581,649 Deaths from COVID-19 Virus Pandemic - Worldometer</title>
<meta content="Live statistics and coronavirus news tracking the number of confirmed cases, recovered patients, tests, and death toll due to the COVID-19 coronavirus from Wuhan, China. Coronavirus counter with new cases, deaths, and number of tests per 1 Million population. Historical data and info. Daily charts, graphs, news and updates" name="description"/>
<link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/favicon/manifest.json" rel="manifest"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<meta content="http://www.worldometers.info/img/worldometers-fb.jpg" property="og:image"/>
<link href="/css/bootstrap.min.css" rel="stylesheet"/>
<link href="/wm16.css" rel="stylesheet"/>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/ie10-viewport-bug-workaround.js"></script>
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example2').dataTable( {
        "scrollCollapse": true,
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#table3').dataTable( {
        "scrollCollapse": true,
				 "order": [[ 1, 'desc' ]],
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example').dataTable( {
        "scrollCollapse": true,
		"searching": false,

		"sDom": '<"top">rt<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
$(document).ready(function() {
	$('#popbycountry').dataTable();
} );
	</script>
<script data-cfasync="false" type="text/javascript">
  var freestar = freestar || {};
  freestar.hitTime = Date.now();
  freestar.queue = freestar.queue || [];
  freestar.config = freestar.config || {};
  freestar.debug = window.location.search.indexOf('fsdebug') === -1 ? false : true;
  freestar.config.enabled_slots = [];
  !function(a,b){var c=b.getElementsByTagName("script")[0],d=b.createElement("script"),e="https://a.pub.network/worldometers-info";e+=freestar.debug?"/qa/pubfig.min.js":"/pubfig.min.js",d.async=!0,d.src=e,c.parentNode.insertBefore(d,c)}(window,document);
</script>
</head>
<body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1438574-2', 'auto');
  ga('send', 'pageview');
</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-1438574-30"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1438574-30');
</script>
<link href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" rel="stylesheet" type="text/css"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#efefef",
      "text": "#404040"
    },
    "button": {
      "background": "#8ec760",
      "text": "#ffffff"
    }
  },
  "theme": "classic",
  "content": {
    "href": "http://www.worldometers.info/policy/"
  }
})});
</script>
<style type="text/css">
    .style1 {
        color: #666666
    }
</style>
<div class="navbar navbar-default">
<div class="container">
<div class="navbar-header">
<div class="logo"><a class="navbar-brand" href="/"><img border="0" src="/img/worldometers-logo.gif" title="Worldometer"/></a></div>
<button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="navbar-collapse collapse" id="navbar-main">
<ul class="nav navbar-nav">
<li><a href="/coronavirus/"><span style="color:#FF9900; font-weight:bold">Coronavirus</span></a></li>
<li><a href="/population/">Population</a></li>
</ul>
</div>
</div>
</div>
<div class="container">
<div class="row">
<div style="text-align:left; margin-bottom:10px">
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle" data-ad-client="ca-pub-3701697624350410" data-ad-slot="3287840995" style="display:inline-block;width:970px;height:90px"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
</div>
<div class="row"> <div class="col-md-8">
<div class="content-inner">
<style>
    .number-table {
        font-size: 20px;
        font-weight: bold
    }

    .number-table-main {
        font-size: 24px;
        font-weight: bold
    }
</style>
<script src="/js/highcharts.js"></script>
<style type="text/css">
    <!--
    .source { }

    .style2 {
        color: #FF0000
    }

    .style4 {
        color: #FF0000;
        font-weight: bold;
    }

    .style6 {
        font-size: 12px;
        color: #bbb;
        font-weight: bold;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source11 {
        font-size: 12px;
        color: #bbb;
    }    .source111 {

    } .source1111 {
        font-size: 12px;
        color: #bbb;
    }



    -->
</style>
<div class="label-counter" id="page-top">COVID-19 Coronavirus Pandemic</div>
<div style="font-size:13px; color:#999; margin-top:5px; text-align:center">Last updated: March 05, 2021, 02:56 GMT</div>
<div style="margin-top:20px; text-align:center; font-size:14px"><a href="/coronavirus/coronavirus-cases/"> </a><a href="/coronavirus/worldwide-graphs/">Graphs</a> - <a href="#countries">Countries</a> - <a href="#news">News</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Coronavirus Cases:</h1>
<div class="maincounter-number">
<span style="color:#aaa">116,216,580 </span>
</div>
</div>
<div style="text-align:center "><a href="#countries">view by country</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Deaths:</h1>
<div class="maincounter-number">
<span>2,581,649</span>
</div>
</div>
<div id="maincounter-wrap" style="margin-top:15px;">
<h1>Recovered:</h1>
<div class="maincounter-number" style="color:#8ACA2B ">
<span>91,884,249</span>
</div>
</div>
<div style="margin-top:50px;"></div>
<style>
    .panel_flip {
        position: relative;
        height: 100%;
    }

    .panel_front {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_back {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateY(-180deg);
        -moz-transform: rotateY(-180deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_flip.flip .panel_front {

        z-index: 900;
        -webkit-transform: rotateY(180deg);
        -moz-transform: rotateY(180deg);
    }

    .panel_flip.flip .panel_back {

        z-index: 1000;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
    }
</style>
<script>
    $(function() {

        $('.flip_cases_front').on('click', function() {


            $(this).parent().parent().addClass('flip');
        });

        $('.flip_cases_back').on('click', function() {


            $(this).parent().parent().removeClass('flip');
        });
    });
</script>
<div class="col-md-6">
<div class="panel panel-default">
<div class="panel-heading" style="text-align:center">
<span class="panel-title" style="font-size:18px; text-transform:uppercase; font-weight:100">
Active Cases
</span>
</div>
<div class="panel-body" style="text-align:center; height:200px;">
<div class="panel_flip">
<div class="panel_front" style="width:100%;height:100%;">
<div class="number-table-main">21,750,682</div>
<div style="font-size:13.5px">Currently Infected Patients</div>
<div style="padding-top:20px;position:relative;text-align:center; ">
<div style="float:left; text-align:center">
<span class="number-table" style="color:#8080FF">21,660,935</span> (<strong>99.6</strong>%)
<div style="font-size:13px">in Mild Condition</div><br/>
</div>
<div style="float:right; text-align:center"><span class="number-table" style="color:red ">89,747</span> (<strong>0.4</strong>%)
<div style="font-size:13px">Serious or Critical</div><br/>
</div>
</div>
<a class="flip_cases_front" href="javascript: void(0);" style="clear: both;display: block;position:absolute;bottom:-8px;width:100%;">Show Graph</a>
</div>
<div class="panel_back" style="width:100%;height:100%;">
<div id="total-currently-infected-linear"></div>
<script type="text/javascript">
    Highcharts.setOptions({
        lang: {
            thousandsSep: ','
        }
    });

    var y_labels = ['0', '20,000', '40,000', '60,000', '140', '180', '200', '240'];
    Highcharts.chart('total-currently-infected-linear', {


        chart: {
            type: 'line',
            height: (9 / 16 * 100) + '%'
        },

        title: {
            text: null

        },

        /*subtitle: {
            text: '(Number of Infected People)'
        },*/

        xAxis: {
            categories: ["Jan 22, 2020","Jan 23, 2020","Jan 24, 2020","Jan 25, 2020","Jan 26, 2020","Jan 27, 2020","Jan 28, 2020","Jan 29, 2020","Jan 30, 2020","Jan 31, 2020","Feb 01, 2020","Feb 02, 2020","Feb 03, 2020","Feb 04, 2020","Feb 05, 2020","Feb 06, 2020","Feb 07, 2020","Feb 08, 2020","Feb 09, 2020","Feb 10, 2020","Feb 11, 2020","Feb 12, 2020","Feb 13, 2020","Feb 14, 2020","Feb 15, 2020","Feb 16, 2020","Feb 17, 2020","Feb 18, 2020","Feb 19, 2020","Feb 20, 2020","Feb 21, 2020","Feb 22, 2020","Feb 23, 2020","Feb 24, 2020","Feb 25, 2020","Feb 26, 2020","Feb 27, 2020","Feb 28, 2020","Feb 29, 2020","Mar 01, 2020","Mar 02, 2020","Mar 03, 2020","Mar 04, 2020","Mar 05, 2020","Mar 06, 2020","Mar 07, 2020","Mar 08, 2020","Mar 09, 2020","Mar 10, 2020","Mar 11, 2020","Mar 12, 2020","Mar 13, 2020","Mar 14, 2020","Mar 15, 2020","Mar 16, 2020","Mar 17, 2020","Mar 18, 2020","Mar 19, 2020","Mar 20, 2020","Mar 21, 2020","Mar 22, 2020","Mar 23, 2020","Mar 24, 2020","Mar 25, 2020","Mar 26, 2020","Mar 27, 2020","Mar 28, 2020","Mar 29, 2020","Mar 30, 2020","Mar 31, 2020","Apr 01, 2020","Apr 02, 2020","Apr 03, 2020","Apr 04, 2020","Apr 05, 2020","Apr 06, 2020","Apr 07, 2020","Apr 08, 2020","Apr 09, 2020","Apr 10, 2020","Apr 11, 2020","Apr 12, 2020","Apr 13, 2020","Apr 14, 2020","Apr 15, 2020","Apr 16, 2020","Apr 17, 2020","Apr 18, 2020","Apr 19, 2020","Apr 20, 2020","Apr 21, 2020","Apr 22, 2020","Apr 23, 2020","Apr 24, 2020","Apr 25, 2020","Apr 26, 2020","Apr 27, 2020","Apr 28, 2020","Apr 29, 2020","Apr 30, 2020","May 01, 2020","May 02, 2020","May 03, 2020","May 04, 2020","May 05, 2020","May 06, 2020","May 07, 2020","May 08, 2020","May 09, 2020","May 10, 2020","May 11, 2020","May 12, 2020","May 13, 2020","May 14, 2020","May 15, 2020","May 16, 2020","May 17, 2020","May 18, 2020","May 19, 2020","May 20, 2020","May 21, 2020","May 22, 2020","May 23, 2020","May 24, 2020","May 25, 2020","May 26, 2020","May 27, 2020","May 28, 2020","May 29, 2020","May 30, 2020","May 31, 2020","Jun 01, 2020","Jun 02, 2020","Jun 03, 2020","Jun 04, 2020","Jun 05, 2020","Jun 06, 2020","Jun 07, 2020","Jun 08, 2020","Jun 09, 2020","Jun 10, 2020","Jun 11, 2020","Jun 12, 2020","Jun 13, 2020","Jun 14, 2020","Jun 15, 2020","Jun 16, 2020","Jun 17, 2020","Jun 18, 2020","Jun 19, 2020","Jun 20, 2020","Jun 21, 2020","Jun 22, 2020","Jun 23, 2020","Jun 24, 2020","Jun 25, 2020","Jun 26, 2020","Jun 27, 2020","Jun 28, 2020","Jun 29, 2020","Jun 30, 2020","Jul 01, 2020","Jul 02, 2020","Jul 03, 2020","Jul 04, 2020","Jul 05, 2020","Jul 06, 2020","Jul 07, 2020","Jul 08, 2020","Jul 09, 2020","Jul 10, 2020","Jul 11, 2020","Jul 12, 2020","Jul 13, 2020","Jul 14, 2020","Jul 15, 2020","Jul 16, 2020","Jul 17, 2020","Jul 18, 2020","Jul 19, 2020","Jul 20, 2020","Jul 21, 2020","Jul 22, 2020","Jul 23, 2020","Jul 24, 2020","Jul 25, 2020","Jul 26, 2020","Jul 27, 2020","Jul 28, 2020","Jul 29, 2020","Jul 30, 2020","Jul 31, 2020","Aug 01, 2020","Aug 02, 2020","Aug 03, 2020","Aug 04, 2020","Aug 05, 2020","Aug 06, 2020","Aug 07, 2020","Aug 08, 2020","Aug 09, 2020","Aug 10, 2020","Aug 11, 2020","Aug 12, 2020","Aug 13, 2020","Aug 14, 2020","Aug 15, 2020","Aug 16, 2020","Aug 17, 2020","Aug 18, 2020","Aug 19, 2020","Aug 20, 2020","Aug 21, 2020","Aug 22, 2020","Aug 23, 2020","Aug 24, 2020","Aug 25, 2020","Aug 26, 2020","Aug 27, 2020","Aug 28, 2020","Aug 29, 2020","Aug 30, 2020","Aug 31, 2020","Sep 01, 2020","Sep 02, 2020","Sep 03, 2020","Sep 04, 2020","Sep 05, 2020","Sep 06, 2020","Sep 07, 2020","Sep 08, 2020","Sep 09, 2020","Sep 10, 2020","Sep 11, 2020","Sep 12, 2020","Sep 13, 2020","Sep 14, 2020","Sep 15, 2020","Sep 16, 2020","Sep 17, 2020","Sep 18, 2020","Sep 19, 2020","Sep 20, 2020","Sep 21, 2020","Sep 22, 2020","Sep 23, 2020","Sep 24, 2020","Sep 25, 2020","Sep 26, 2020","Sep 27, 2020","Sep 28, 2020","Sep 29, 2020","Sep 30, 2020","Oct 01, 2020","Oct 02, 2020","Oct 03, 2020","Oct 04, 2020","Oct 05, 2020","Oct 06, 2020","Oct 07, 2020","Oct 08, 2020","Oct 09, 2020","Oct 10, 2020","Oct 11, 2020","Oct 12, 2020","Oct 13, 2020","Oct 14, 2020","Oct 15, 2020","Oct 16, 2020","Oct 17, 2020","Oct 18, 2020","Oct 19, 2020","Oct 20, 2020","Oct 21, 2020","Oct 22, 2020","Oct 23, 2020","Oct 24, 2020","Oct 25, 2020","Oct 26, 2020","Oct 27, 2020","Oct 28, 2020","Oct 29, 2020","Oct 30, 2020","Oct 31, 2020","Nov 01, 2020","Nov 02, 2020","Nov 03, 2020","Nov 04, 2020","Nov 05, 2020","Nov 06, 2020","Nov 07, 2020","Nov 08, 2020","Nov 09, 2020","Nov 10, 2020","Nov 11, 2020","Nov 12, 2020","Nov 13, 2020","Nov 14, 2020","Nov 15, 2020","Nov 16, 2020","Nov 17, 2020","Nov 18, 2020","Nov 19, 2020","Nov 20, 2020","Nov 21, 2020","Nov 22, 2020","Nov 23, 2020","Nov 24, 2020","Nov 25, 2020","Nov 26, 2020","Nov 27, 2020","Nov 28, 2020","Nov 29, 2020","Nov 30, 2020","Dec 01, 2020","Dec 02, 2020","Dec 03, 2020","Dec 04, 2020","Dec 05, 2020","Dec 06, 2020","Dec 07, 2020","Dec 08, 2020","Dec 09, 2020","Dec 10, 2020","Dec 11, 2020","Dec 12, 2020","Dec 13, 2020","Dec 14, 2020","Dec 15, 2020","Dec 16, 2020","Dec 17, 2020","Dec 18, 2020","Dec 19, 2020","Dec 20, 2020","Dec 21, 2020","Dec 22, 2020","Dec 23, 2020","Dec 24, 2020","Dec 25, 2020","Dec 26, 2020","Dec 27, 2020","Dec 28, 2020","Dec 29, 2020","Dec 30, 2020","Dec 31, 2020","Jan 01, 2021","Jan 02, 2021","Jan 03, 2021","Jan 04, 2021","Jan 05, 2021","Jan 06, 2021","Jan 07, 2021","Jan 08, 2021","Jan 09, 2021","Jan 10, 2021","Jan 11, 2021","Jan 12, 2021","Jan 13, 2021","Jan 14, 2021","Jan 15, 2021","Jan 16, 2021","Jan 17, 2021","Jan 18, 2021","Jan 19, 2021","Jan 20, 2021","Jan 21, 2021","Jan 22, 2021","Jan 23, 2021","Jan 24, 2021","Jan 25, 2021","Jan 26, 2021","Jan 27, 2021","Jan 28, 2021","Jan 29, 2021","Jan 30, 2021","Jan 31, 2021","Feb 01, 2021","Feb 02, 2021","Feb 03, 2021","Feb 04, 2021","Feb 05, 2021","Feb 06, 2021","Feb 07, 2021","Feb 08, 2021","Feb 09, 2021","Feb 10, 2021","Feb 11, 2021","Feb 12, 2021","Feb 13, 2021","Feb 14, 2021","Feb 15, 2021","Feb 16, 2021","Feb 17, 2021","Feb 18, 2021","Feb 19, 2021","Feb 20, 2021","Feb 21, 2021","Feb 22, 2021","Feb 23, 2021","Feb 24, 2021","Feb 25, 2021","Feb 26, 2021","Feb 27, 2021","Feb 28, 2021","Mar 01, 2021","Mar 02, 2021","Mar 03, 2021","Mar 04, 2021"]
        },

        yAxis: {
            title: {
                text: 'Currently Infected',
                enabled: false

            }
            /*tickInterval: 20000,*/

            /*categories: [0,50000],
            labels: {

                format: "{value:,.%0f}"
            }*/
            /*labels: {
                step: 15
            }*/

        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            enabled: false
        },

        credits: {
            enabled: false
        },
        plotOptions: {
            line: {
                marker: {
                    enabled: false
                }
            }
        },


        series: [{
            name: 'Currently Infected',
            color: '#00DDDD',
            lineWidth: 5,

In [3]:
soup.table

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>33,890,918</td>
<td>+7,521</td>
<td>771,371</td>
<td>+822</td>
<td>23,706,426</td>
<td>+5,319</td>
<td>9,413,121</td>
<td>20,461</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>25,312,988</td>
<td>+430</td>
<td>401,501</td>
<td>+8</td>
<td>23,765,863</td>
<td>+411</td>
<td>1,145,624</td>
<td>21,968</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>18,329,295</td>
<td>+969</td>
<td>475,595</td>
<td>+27</td>
<td>16,566,888</td>
<td>+606</td>
<td>1,286,812</td>
<td>19,066</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>34,664,874</td>
<td></td>
<td>826,911</td>
<td></td>
<td>24,282,703</td>
<td></td>
<td>9,555,260</td>
<td>25,776</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>3,966,393</td>
<td></td>
<td>105,165</td>
<td></td>
<td>3,527,350</td>
<td></td>
<td>333,878</td>
<td>2,474</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>51,391</td>
<td>+14</td>
<td>1,091</td>
<td></td>
<td>34,313</td>
<td>+3</td>
<td>15,987</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>116,216,580</td>
<td>+8,934</td>
<td>2,581,649</td>
<td>+857</td>
<td>91,884,249</td>
<td>+6,339</td>
<td>21,750,682</td>
<td>89,747</td>
<td>14,910</td>
<td>331.2</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">29,526,086</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">533,636 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">20,093,442</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">8,899,008</td>
<td style="font-weight: bold; text-align:right">13,934</td>
<td style="font-weight: bold; text-align:right">88,851</td>
<td style="font-weight: bold; text-align:right">1,606</td>
<td style="font-weight: bold; text-align:right">365,017,193</td>
<td style="font-weight: bold; text-align:right">1,098,425</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">332,309,730</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>11</td><td>623</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">11,173,572</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">157,584 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">10,838,021</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">177,967</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">8,044</td>
<td style="font-weight: bold; text-align:right">113</td>
<td style="font-weight: bold; text-align:right">219,178,908</td>
<td style="font-weight: bold; text-align:right">157,782</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,389,123,461</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>124</td><td>8,815</td><td>6</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">10,796,506</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">261,188 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">9,637,020</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">898,298</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">50,551</td>
<td style="font-weight: bold; text-align:right">1,223</td>
<td style="font-weight: bold; text-align:right">28,600,000</td>
<td style="font-weight: bold; text-align:right">133,910</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">213,576,312</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>20</td><td>818</td><td>7</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">4,290,135</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">87,823 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">3,869,857</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">332,455</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">29,389</td>
<td style="font-weight: bold; text-align:right">602</td>
<td style="font-weight: bold; text-align:right">112,100,000</td>
<td style="font-weight: bold; text-align:right">767,931</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,976,706</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>34</td><td>1,662</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">4,201,358</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">124,025 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">3,096,564</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">980,769</td>
<td style="font-weight: bold; text-align:right">1,647</td>
<td style="font-weight: bold; text-align:right">61,670</td>
<td style="font-weight: bold; text-align:right">1,821</td>
<td style="font-weight: bold; text-align:right">93,148,314</td>
<td style="font-weight: bold; text-align:right">1,367,290</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,126,222</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>16</td><td>549</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">3,835,595</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">87,835 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">262,690</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">3,485,070</td>
<td style="font-weight: bold; text-align:right">3,633</td>
<td style="font-weight: bold; text-align:right">58,674</td>
<td style="font-weight: bold; text-align:right">1,344</td>
<td style="font-weight: bold; text-align:right">53,959,451</td>
<td style="font-weight: bold; text-align:right">825,435</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,370,939</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>17</td><td>744</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">3,142,358</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">70,501 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">2,722,304</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">349,553</td>
<td style="font-weight: bold; text-align:right">2,615</td>
<td style="font-weight: bold; text-align:right">67,192</td>
<td style="font-weight: bold; text-align:right">1,507</td>
<td style="font-weight: bold; text-align:right">39,313,189</td>
<td style="font-weight: bold; text-align:right">840,618</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,767,004</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>15</td><td>663</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">2,999,119</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">98,974 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">2,453,706</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">446,439</td>
<td style="font-weight: bold; text-align:right">2,475</td>
<td style="font-weight: bold; text-align:right">49,653</td>
<td style="font-weight: bold; text-align:right">1,639</td>
<td style="font-weight: bold; text-align:right">41,338,022</td>
<td style="font-weight: bold; text-align:right">684,384</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,401,757</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>20</td><td>610</td><td>1</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">2,746,158</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">28,839 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">2,601,137</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">116,182</td>
<td style="font-weight: bold; text-align:right">1,220</td>
<td style="font-weight: bold; text-align:right">32,327</td>
<td style="font-weight: bold; text-align:right">339</td>
<td style="font-weight: bold; text-align:right">33,716,746</td>
<td style="font-weight: bold; text-align:right">396,907</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">84,948,754</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>31</td><td>2,946</td><td>3</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">2,484,306</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">72,007 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">2,283,400</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">128,899</td>
<td style="font-weight: bold; text-align:right">2,848</td>
<td style="font-weight: bold; text-align:right">29,588</td>
<td style="font-weight: bold; text-align:right">858</td>
<td style="font-weight: bold; text-align:right">45,114,160</td>
<td style="font-weight: bold; text-align:right">537,300</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,964,573</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>34</td><td>1,166</td><td>2</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>
<td style="font-weight: bold; text-align:right">2,266,211</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">60,189 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">2,164,438</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">41,584</td>
<td style="font-weight: bold; text-align:right">2,240</td>
<td style="font-weight: bold; text-align:right">44,221</td>
<td style="font-weight: bold; text-align:right">1,174</td>
<td style="font-weight: bold; text-align:right">11,614,196</td>
<td style="font-weight: bold; text-align:right">226,631</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,247,260</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>23</td><td>851</td><td>4</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>
<td style="font-weight: bold; text-align:right">2,133,963</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">52,644 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">1,928,377</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">152,942</td>
<td style="font-weight: bold; text-align:right">3,521</td>
<td style="font-weight: bold; text-align:right">46,926</td>
<td style="font-weight: bold; text-align:right">1,158</td>
<td style="font-weight: bold; text-align:right">7,617,966</td>
<td style="font-weight: bold; text-align:right">167,521</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/argentina-population/">45,474,610</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>21</td><td>864</td><td>6</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>
<td style="font-weight: bold; text-align:right">2,112,508</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+7,521</td>
<td style="font-weight: bold; text-align:right;">188,866 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+822</td>
<td style="font-weight: bold; text-align:right">1,655,549</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5,319</td>
<td style="text-align:right;font-weight:bold;">268,093</td>
<td style="font-weight: bold; text-align:right">4,798</td>
<td style="font-weight: bold; text-align:right">16,270</td>
<td style="font-weight: bold; text-align:right">1,455</td>
<td style="font-weight: bold; text-align:right">5,555,699</td>
<td style="font-weight: bold; text-align:right">42,788</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/mexico-population/">129,842,915</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>61</td><td>687</td><td>23</td>
</tr>
<tr style="">

In [4]:
tags=soup.find_all("tr")
tags

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">Tot Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>33,890,918</td>
 <td>+7,521</td>
 <td>771,371</td>
 <td>+822</td>
 <td>23,706,426</td>
 <td>+5,319</td>
 <td>9,413,121</td>
 <td>20,461</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>25,312,988</td>
 <td>+430</td>
 <td>401,501</td>
 <td>+8</td>
 <td>23,765,863</td>
 <td>+411</td>
 <td>1,145,624</td>
 <td>21,968</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>18,329,295</td>
 <td>+969</td>
 <td>475,595</td>
 <td>+27</td>
 <td>16,566,888</td>
 <td>+606</td>
 <td>1,286,812</td>
 <td>19,066</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>34,664,874</td>
 <td></td>
 <td>826,911</td>
 <td></td>
 <td>24,282,703</td>
 <td></td>
 <td>9,555,260</td>
 <td>25,776</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>3,966,393</td>
 <td></td>
 <td>105,165</td>
 <td></td>
 <td>3,527,350</td>
 <td></td>
 <td>333,878</td>
 <td>2,474</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>51,391</td>
 <td>+14</td>
 <td>1,091</td>
 <td></td>
 <td>34,313</td>
 <td>+3</td>
 <td>15,987</td>
 <td>2</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>116,216,580</td>
 <td>+8,934</td>
 <td>2,581,649</td>
 <td>+857</td>
 <td>91,884,249</td>
 <td>+6,339</td>
 <td>21,750,682</td>
 <td>89,747</td>
 <td>14,910</td>
 <td>331.2</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">29,526,086</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">533,636 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">20,093,442</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">8,899,008</td>
 <td style="font-weight: bold; text-align:right">13,934</td>
 <td style="font-weight: bold; text-align:right">88,851</td>
 <td style="font-weight: bold; text-align:right">1,606</td>
 <td style="font-weight: bold; text-align:right">365,017,193</td>
 <td style="font-weight: bold; text-align:right">1,098,425</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">332,309,730</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <td>11</td><td>623</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">11,173,572</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">157,584 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">10,838,021</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">177,967</td>
 <td style="font-weight: bold; text-align:right">8,944</td>
 <td style="font-weight: bold; text-align:right">8,044</td>
 <td style="font-weight: bold; text-align:right">113</td>
 <td style="font-weight: bold; text-align:right">219,178,908</td>
 <td style="font-weight: bold; text-align:right">157,782</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,389,123,461</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>124</td><td>8,815</td><td>6</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">10,796,506</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">261,188 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">9,637,020</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">898,298</td>
 <td style="font-weight: bold; text-align:right">8,318</td>
 <td style="font-weight: bold; text-align:right">50,551</td>
 <td style="font-weight: bold; text-align:right">1,223</td>
 <td style="font-weight: bold; text-align:right">28,600,000</td>
 <td style="font-weight: bold; text-align:right">133,910</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">213,576,312</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>20</td><td>818</td><td>7</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">4,290,135</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">87,823 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">3,869,857</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">332,455</td>
 <td style="font-weight: bold; text-align:right">2,300</td>
 <td style="font-weight: bold; text-align:right">29,389</td>
 <td style="font-weight: bold; text-align:right">602</td>
 <td style="font-weight: bold; text-align:right">112,100,000</td>
 <td style="font-weight: bold; text-align:right">767,931</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,976,706</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>34</td><td>1,662</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">4,201,358</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">124,025 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">3,096,564</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">980,769</td>
 <td style="font-weight: bold; text-align:right">1,647</td>
 <td style="font-weight: bold; text-align:right">61,670</td>
 <td style="font-weight: bold; text-align:right">1,821</td>
 <td style="font-weight: bold; text-align:right">93,148,314</td>
 <td style="font-weight: bold; text-align:right">1,367,290</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,126,222</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>16</td><td>549</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">3,835,595</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">87,835 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">262,690</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">3,485,070</td>
 <td style="font-weight: bold; text-align:right">3,633</td>
 <td style="font-weight: bold; text-align:right">58,674</td>
 <td style="font-weight: bold; text-align:right">1,344</td>
 <td style="font-weight: bold; text-align:right">53,959,451</td>
 <td style="font-weight: bold; text-align:right">825,435</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,370,939</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>17</td><td>744</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
 <td style="font-weight: bold; text-align:right">3,142,358</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">70,501 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">2,722,304</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">349,553</td>
 <td style="font-weight: bold; text-align:right">2,615</td>
 <td style="font-weight: bold; text-align:right">67,192</td>
 <td style="font-weight: bold; text-align:right">1,507</td>
 <td style="font-weight: bold; text-align:right">39,313,189</td>
 <td style="font-weight: bold; text-align:right">840,618</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,767,004</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>15</td><td>663</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">2,999,119</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">98,974 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">2,453,706</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">446,439</td>
 <td style="font-weight: bold; text-align:right">2,475</td>
 <td style="font-weight: bold; text-align:right">49,653</td>
 <td style="font-weight: bold; text-align:right">1,639</td>
 <td style="font-weight: bold; text-align:right">41,338,022</td>
 <td style="font-weight: bold; text-align:right">684,384</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,401,757</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>20</td><td>610</td><td>1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
 <td style="font-weight: bold; text-align:right">2,746,158</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">28,839 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">2,601,137</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">116,182</td>
 <td style="font-weight: bold; text-align:right">1,220</td>
 <td style="font-weight: bold; text-align:right">32,327</td>
 <td style="font-weight: bold; text-align:right">339</td>
 <td style="font-weight: bold; text-align:right">33,716,746</td>
 <td style="font-weight: bold; text-align:right">396,907</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">84,948,754</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>31</td><td>2,946</td><td>3</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">2,484,306</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">72,007 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">2,283,400</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">128,899</td>
 <td style="font-weight: bold; text-align:right">2,848</td>
 <td style="font-weight: bold; text-align:right">29,588</td>
 <td style="font-weight: bold; text-align:right">858</td>
 <td style="font-weight: bold; text-align:right">45,114,160</td>
 <td style="font-weight: bold; text-align:right">537,300</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,964,573</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>34</td><td>1,166</td><td>2</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>
 <td style="font-weight: bold; text-align:right">2,266,211</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">60,189 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">2,164,438</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">41,584</td>
 <td style="font-weight: bold; text-align:right">2,240</td>
 <td style="font-weight: bold; text-align:right">44,221</td>
 <td style="font-weight: bold; text-align:right">1,174</td>
 <td style="font-weight: bold; text-align:right">11,614,196</td>
 <td style="font-weight: bold; text-align:right">226,631</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,247,260</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>23</td><td>851</td><td>4</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>
 <td style="font-weight: bold; text-align:right">2,133,963</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">52,644 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">1,928,377</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">152,942</td>
 <td style="font-weight: bold; text-align:right">3,521</td>
 <td style="font-weight: bold; text-align:right">46,926</td>
 <td style="font-weight: bold; text-align:right">1,158</td>
 <td style="font-weight: bold; text-align:right">7,617,966</td>
 <td style="font-weight: bold; text-align:right">167,521</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/argentina-population/">45,474,610</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>21</td><td>864</td><td>6</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>
 <td style="font-weight: bold; text-align:right">2,112,508</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+7,521</td>
 <td style="font-weight: bold; text-align:right;">188,866 </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+822</td>
 <td style="font-weight: bold; text-align:right">1,655,549</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5,319</td>
 <td style="text-align:right;font-weight:bold;">268,093</td>
 <td style="font-weight: bold; text-align:right">4,798</td>
 <td style="font-weight: bold; text-align:right">16,270</td>
 <td style="font-weight: bold; text-align:right">1,455</td>
 <td style="font-weight: bold; text-align:right">5,555,699</td>

In [5]:
for i in tags:
    print(i.text)

#
Country,Other
TotalCases
NewCases
TotalDeaths
NewDeaths
TotalRecovered
NewRecovered
ActiveCases
Serious,Critical
Tot Cases/1M pop
Deaths/1M pop
TotalTests
Tests/
1M pop

Population
Continent
1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl




North America

33,890,918
+7,521
771,371
+822
23,706,426
+5,319
9,413,121
20,461





North America








Asia

25,312,988
+430
401,501
+8
23,765,863
+411
1,145,624
21,968





Asia








South America

18,329,295
+969
475,595
+27
16,566,888
+606
1,286,812
19,066





South America








Europe

34,664,874

826,911

24,282,703

9,555,260
25,776





Europe








Africa

3,966,393

105,165

3,527,350

333,878
2,474





Africa








Oceania

51,391
+14
1,091

34,313
+3
15,987
2





Australia/Oceania










721

15

706

0
0













World
116,216,580
+8,934
2,581,649
+857
91,884,249
+6,339
21,750,682
89,747
14,910
331.2



All






1
USA
29,526,086

533,636

20,093,442

8,899,008
13,934
88,851
1,606
365,017,193
1,098,425
332,309,730
North America
116231


2
India
11,173,572

157,584

10,838,021

177,967
8,944
8,044
113
219,178,908
157,782
1,389,123,461
Asia
1248,8156


3
Brazil
10,796,506

261,188

9,637,020

898,298
8,318
50,551
1,223
28,600,000
133,910
213,576,312
South America
208187


4
Russia
4,290,135

87,823

3,869,857

332,455
2,300
29,389
602
112,100,000
767,931
145,976,706
Europe
341,6621


5
UK
4,201,358

124,025

3,096,564

980,769
1,647
61,670
1,821
93,148,314
1,367,290
68,126,222
Europe
165491


6
France
3,835,595

87,835

262,690

3,485,070
3,633
58,674
1,344
53,959,451
825,435
65,370,939
Europe
177441


7
Spain
3,142,358

70,501

2,722,304

349,553
2,615
67,192
1,507
39,313,189
840,618
46,767,004
Europe
156631


8
Italy
2,999,119

98,974

2,453,706

446,439
2,475
49,653
1,639
41,338,022
684,384
60,401,757
Europe
206101


9
Turkey
2,746,158

28,839

2,601,137

116,182
1,220
32,327
339
33,716,746
396,907
84,948,754
Asia
312,9463


10
Germany
2,484,306

72,007

2,283,400

128,899
2,848
29,588
858
45,114,160
537,300
83,964,573
Europe
341,1662


11
Colombia
2,266,211

60,189

2,164,438

41,584
2,240
44,221
1,174
11,614,196
226,631
51,247,260
South America
238514


12
Argentina
2,133,963

52,644

1,928,377

152,942
3,521
46,926
1,158
7,617,966
167,521
45,474,610
South America
218646


13
Mexico
2,112,508
+7,521
188,866
+822
1,655,549
+5,319
268,093
4,798
16,270
1,455
5,555,699
42,788
129,842,915
North America
6168723


14
Poland
1,750,659

44,649

1,448,619

257,391
1,650
46,291
1,181
10,070,976
266,297
37,818,609
Europe
228474


15
Iran
1,665,103

60,431

1,420,958

183,714
3,760
19,655
713
11,092,900
130,945
84,714,448
Asia
511,4028


16
South Africa
1,517,666

50,462

1,436,010

31,194
546
25,375
844
9,178,323
153,457
59,810,579
Africa
391,1857


17
Ukraine
1,374,762

26,591

1,186,873

161,298
177
31,563
611
7,021,993
161,218
43,555,898
Europe
321,6386


18
Indonesia
1,361,098

36,897

1,176,356

147,845

4,941
134
11,004,843
39,950
275,466,894
Asia
2027,46625


19
Peru
1,349,847

47,306

1,250,047

52,494
2,176
40,560
1,421
7,757,176
233,089
33,279,921
South America
257044


20
Czechia
1,284,288

21,128

1,104,592

158,568
1,708
119,776
1,970
8,389,822
782,459
10,722,385
Europe
85071


21
Netherlands
1,105,544

15,730

N/A
N/A
N/A
549
64,424
917
6,970,400
406,190
17,160,446
Europe
161,0912


22
Canada
878,391

22,151

826,337

29,903
572
23,137
583
24,763,481
652,277
37,964,686
North America
431,7142


23
Chile
840,119

20,838

793,819

25,462
1,711
43,696
1,084
9,538,043
496,087
19,226,558
South America
239232


24
Romania
816,589

20,684

749,673

46,232
1,070
42,640
1,080
6,439,713
336,264
19,150,793
Europe
239263


25
Portugal
807,456

16,458

727,053

63,945
399
79,344
1,617
8,318,706
817,434
10,176,609
Europe
136181


26
Israel
793,407

5,822

746,228

41,357
702
86,262
633
12,199,957
1,326,430
9,197,590
Asia
121,5801


27
Belgium
777,608

22,169

52,863

702,576
426
66,899
1,907
9,587,540
824,833
11,623,613
Europe
155241


28
Iraq
713,994

13,507

650,015

50,472
387
17,489
331
7,008,505
171,671
40,825,159
Asia
573,0236


29
Sweden
680,130

12,977

N/A
N/A
N/A
231
67,063
1,280
6,139,911
605,415
10,141,664
Europe
157822


30
Pakistan
585,435

13,076

555,242

17,117
1,559
2,616
58
9,097,413
40,657
223,760,893
Asia
38217,11225


31
Philippines
584,667

12,404

535,037

37,226
785
5,288
112
8,875,386
80,277
110,559,647
Asia
1898,91312


32
Switzerland
561,068

10,022

516,798

34,248
161
64,511
1,152
5,167,034
594,102
8,697,214
Europe
168682


33
Bangladesh
548,549

8,435

500,468

39,646

3,309
51
4,105,321
24,762
165,792,097
Asia
30219,65540


34
Morocco
485,147

8,669

470,933

5,545
241
13,040
233
5,695,763
153,094
37,204,312
Africa
774,2927


35
Serbia
474,807

4,508

400,347

69,952
173
54,491
517
3,002,480
344,575
8,713,566
Europe
181,9333


36
Austria
467,646

8,652

437,202

21,792
302
51,725
957
5,557,591
614,709
9,041,006
Europe
191,0452


37
Hungary
446,178

15,476

328,136

102,566
639
46,266
1,605
3,749,907
388,842
9,643,770
Europe
226233


38
Japan
435,548

8,052

414,774

12,722
398
3,451
64
8,435,308
66,833
126,214,686
Asia
29015,67515


39
Jordan
413,350

4,833

356,648

51,869
377
40,244
471
4,761,823
463,609
10,271,210
Asia
252,1252


40
UAE
402,205

1,286

387,278

13,641

40,339
129
31,520,191
3,161,304
9,970,628
Asia
257,7530


41
Lebanon
386,868

4,919

300,923

81,026
885
56,852
723
3,095,306
454,873
6,804,767
Asia
181,3832


42
Saudi Arabia
378,708

6,514

369,613

2,581
503
10,766
185
13,829,692
393,143
35,177,214
Asia
935,4003


43
Panama
343,281

5,895

329,709

7,677
195
78,729
1,352
1,940,572
445,057
4,360,282
North America
137402


44
Slovakia
317,159

7,560

255,300

54,299
683
58,073
1,384
2,088,725
382,450
5,461,427
Europe
177223


45
Malaysia
307,943

1,153

283,629

23,161
193
9,433
35
6,407,625
196,286
32,644,300
Asia
10628,3125


46
Belarus
291,621

2,011

282,039

7,571

30,868
213
4,951,979
524,173
9,447,224
Europe
324,6982


47
Ecuador
289,735

15,959

247,898

25,878
510
16,257
895
1,025,254
57,525
17,822,631
South America
621,11717


48
Nepal
274,488

2,778

270,683

1,027

9,309
94
2,179,047
73,897
29,487,561
Asia
10710,61514


49
Georgia
271,872

3,553

266,081

2,238

68,241
892
2,788,971
700,044
3,983,992
Asia
151,1211


50
Bulgaria
255,381

10,506

210,638

34,237
440
36,942
1,520
1,714,278
247,978
6,913,014
Europe
276584


51
Bolivia
252,360
+969
11,761
+27
195,705
+606
44,894
71
21,423
998
747,057
63,418
11,779,836
South America
471,00216


52
Croatia
244,872

5,564

235,750

3,558
69
59,898
1,361
1,368,448
334,737
4,088,128
Europe
177353


53
Dominican Republic
241,392

3,139

194,653

43,600
192
22,103
287
1,219,587
111,673
10,921,018
North America
453,4799


54
Azerbaijan
235,647

3,232

229,267

3,148

23,101
317
2,627,991
257,630
10,200,626
Asia
433,1564


55
Tunisia
235,643

8,106

200,984

26,553
263
19,799
681
993,230
83,453
11,901,712
Africa
511,46812


56
Ireland
221,649

4,396

23,364

193,889
103
44,554
884
3,590,079
721,648
4,974,833
Europe
221,1321


57
Kazakhstan
215,610

2,540

199,600

13,470
221
11,391
134
7,419,449
391,993
18,927,501
Asia
887,4523


58
Denmark
213,318

2,374

203,934

7,010
18
36,741
409
17,602,056
3,031,726
5,805,953
Europe
272,4460


59
Costa Rica
206,293

2,829

186,093

17,371
133
40,249
552
700,259
136,625
5,125,394
North America
251,8127


60
Lithuania
200,884

3,294

186,737

10,853
117
74,498
1,222
2,150,037
797,346
2,696,493
Europe
138191


61
Greece
199,496

6,632

172,321

20,543
449
19,203
638
5,425,308
522,236
10,388,605
Europe
521,5662


62
Kuwait
196,497

1,105

183,321

12,071
167
45,560
256
1,822,389
422,542
4,312,914
Asia
223,9032


63
Slovenia
193,285

3,878

178,510

10,897
86
92,964
1,865
930,169
447,384
2,079,131
Europe
115362


64
Palestine
191,203

2,091

171,318

17,794
135
36,908
404
1,202,259
232,071
5,180,562
Asia
272,4784


65
Moldova
191,197

4,049

168,801

18,347
311
47,471
1,005
733,323
182,073
4,027,626
Europe
219955


66
Egypt
184,755

10,871

142,610

31,274
90
1,783
105
1,000,000
9,650
103,625,644
Africa
5619,532104


67
Guatemala
176,876

6,435

163,544

6,897
5
9,752
355
935,380
51,572
18,137,320
North America
1032,81919


68
Armenia
173,307

3,208

164,085

6,014

58,412
1,081
742,038
250,099
2,966,980
Asia
179254


69
Honduras
172,100

4,214

67,239

100,647
403
17,193
421
454,905
45,444
10,010,158
North America
582,37522


70
Qatar
165,546

260

155,070

10,216
111
58,959
93
1,563,932
556,995
2,807,805
Asia
1710,7992


71
Paraguay
164,310

3,256

137,368

23,686
293
22,848
453
765,862
106,498
7,191,352
South America
442,2099


72
Ethiopia
162,954

2,394

137,203

23,357
392
1,394
20
2,158,296
18,469
116,862,573
Africa
71748,81554


73
Nigeria
157,671

1,951

136,335

19,385
10
752
9
1,544,008
7,368
209,546,665
Africa
1,329107,405136


74
Oman
142,896

1,583

133,491

7,822
80
27,516
305
1,550,000
298,467
5,193,202
Asia
363,2813


75
Myanmar
142,000

3,200

131,571

7,229

2,598
59
2,496,367
45,675
54,655,331
Asia
38517,08022


76
Venezuela
140,960

1,364

133,034

6,562
131
4,967
48
2,920,112
102,888
28,381,471
South America
20120,80810


77
Libya
136,587

2,233

123,777

10,577

19,698
322
741,874
106,991
6,933,974
Africa
513,1059


78
Bosnia and Herzegovina
134,892

5,200

117,643

12,049

41,289
1,592
678,280
207,615
3,267,003
Europe
246285


79
Bahrain
124,857

462

117,656

6,739
60
71,724
265
3,151,398
1,810,317
1,740,799
Asia
143,7681


80
Algeria
113,761

3,002

78,672

32,087
23
2,563
68


44,381,005
Africa
39014,784


81
Albania
110,521

1,876

72,853

35,792
46
38,433
652
471,618
164,003
2,875,674
Europe
261,5336


82
Kenya
107,329

1,870

87,099

18,360
61
1,967
34
1,317,617
24,149
54,562,325
Africa
50829,17841


83
North Macedonia
105,269

3,165

93,942

8,162
124
50,530
1,519
533,505
256,085
2,083,316
Europe
206584


84
S. Korea
91,638
+398
1,627
+8
82,560
+398
7,451
135
1,786
32
6,789,011
132,342
51,298,966
Asia
56031,5308


85
Latvia
88,668

1,666

77,830

9,172
74
47,364
890
1,547,619
826,697
1,872,052
Europe
211,1241


86
Kyrgyzstan
86,410

1,468

83,375

1,567
16
13,100
223
756,425
114,674
6,596,295
Asia
764,4939


87
Ghana
85,239

629

79,465

5,145
101
2,705
20
910,673
28,904
31,506,390
Africa
37050,09035


88
Sri Lanka
84,610

489

80,836

3,285

3,940
23
2,122,696
98,851
21,473,757
Asia
25443,91410


89
Zambia
80,687

1,109

76,498

3,080
212
4,309
59
1,113,622
59,467
18,726,681
Africa
23216,88617


90
Uzbekistan
80,035

622

78,587

826
27
2,368
18
1,377,915
40,773
33,794,452
Asia
42254,33225


91
Montenegro
78,060

1,039

68,177

8,844
68
124,276
1,654
287,262
457,336
628,120
Europe
86052


92
Norway
73,493

632

66,014

6,847
18
13,486
116
3,910,562
717,566
5,449,761
Europe
748,6231


93
Estonia
70,610

623

53,360

16,627
44
53,205
469
960,700
723,889
1,327,137
Europe
192,1301


94
Mozambique
61,170

674

44,276

16,220

1,921
21
433,264
13,608
31,838,340
Africa
52047,23873


95
Uruguay
60,945

631

52,612

7,702
79
17,504
181
1,043,679
299,749
3,481,846
South America
575,5183


96
El Salvador
60,800

1,887

56,807

2,106
56
9,342
290
776,696
119,340
6,508,253
North America
1073,4498


97
Finland
60,200

764

46,000

13,436
39
10,854
138
3,407,853
614,412
5,546,528
Europe
927,2602


98
Singapore
59,998

29

59,857

112
1
10,201
5
7,543,963
1,282,704
5,881,296
Asia
98202,8031


99
Luxembourg
56,110

647

52,445

3,018
22
88,669
1,022
2,155,640
3,406,511
632,800
Europe
119780


100
Afghanistan
55,933

2,449

49,362

4,122
1,073
1,416
62
305,242
7,725
39,513,703
Asia
70616,135129


101
Cuba
53,308

336

48,341

4,631
63
4,708
30
2,464,521
217,676
11,321,947
North America
21233,6965


102
Uganda
40,426

334

15,052

25,040

866
7
887,701
19,008
46,700,691
Africa
1,155139,82253


103
Namibia
39,466

436

37,043

1,987
21
15,346
170
307,936
119,740
2,571,701
Africa
655,8988


104
Zimbabwe
36,223

1,483

33,632

1,108
41
2,414
99
345,679
23,033
15,007,997
Africa
41410,12043


105
Cyprus
36,004

232

2,057

33,715
22
29,675
191
2,117,939
1,745,639
1,213,274
Asia
345,2301


106
Cameroon
35,714

551

32,594

2,569
53
1,323
20
905,000
33,535
26,986,485
Africa
75648,97730


107
Senegal
35,247

898

29,889

4,460
48
2,069
53
396,058
23,246
17,037,916
Africa
48318,97343


108
Ivory Coast
33,976

196

32,245

1,535

1,267
7
432,695
16,137
26,813,868
Africa
789136,80562


109
Malawi
32,283

1,058

20,582

10,643
4
1,659
54
201,422
10,351
19,459,402
Africa
60318,39397


110
Botswana
31,746

359

26,760

4,627
1
13,320
151
825,247
346,252
2,383,369
Africa
756,6393


111
Australia
29,021
+14
909

26,189
+3
1,923

1,129
35
14,558,706
566,518
25,698,566
Australia/Oceania
88628,2712


112
Sudan
28,545

1,895

23,084

3,566

641
43


44,532,525
Africa
1,56023,500


113
DRC
26,340

711

20,601

5,028

288
8


91,371,512
Africa
3,469128,511


114
Thailand
26,162

85

25,562

515
1
374
1
1,217,873
17,419
69,918,107
Asia
2,673822,56657


115
Jamaica
24,444

436

13,869

10,139
27
8,231
147
220,388
74,208
2,969,877
North America
1216,81213


116
Malta
23,588

325

20,135

3,128
18
53,326
735
713,482
1,612,987
442,336
Europe
191,3611


117
Angola
20,981

511

19,553

917
10
625
15
193,425
5,766
33,545,658
Africa
1,59965,647173


118
Maldives
20,447

64

17,712

2,671
162
37,386
117
541,164
989,481
546,917
Asia
278,5461


119
Madagascar
19,831

297

19,296

238
23
704
11
119,608
4,247
28,165,495
Africa
1,42094,833235


120
Rwanda
19,334

266

17,682

1,386
11
1,468
20
1,025,213
77,866
13,166,323
Africa
68149,49713


121
French Polynesia
18,459

140

4,842

13,477
2
65,457
496
26,355
93,457
282,002
Australia/Oceania
152,01411


122
Mayotte
18,054

112

2,964

14,978
25
65,128
404
130,738
471,628
277,206
Africa
152,4752


123
Mauritania
17,267

442

16,633

192
14
3,650
93
177,070
37,427
4,731,092
Africa
27410,70427


124
Eswatini
17,129

654

15,039

1,436
36
14,662
560
154,260
132,045
1,168,236
Africa
681,7868


125
French Guiana
16,627

85

9,995

6,547
6
54,723
280
149,894
493,330
303,841
South America
183,5752


126
Guinea
16,420

93

15,091

1,236
24
1,228
7
144,351
10,797
13,370,037
Africa
814143,76493


127
Syria
15,815

1,050

10,123

4,642

889
59


17,784,235
Asia
1,12516,937


128
Cabo Verde
15,621

152

14,959

510
23
27,892
271
122,430
218,608
560,044
Africa
363,6855


129
Gabon
15,254

88

13,495

1,671
19
6,747
39
539,866
238,796
2,260,779
Africa
14825,6914


130
Tajikistan
13,308

90

13,218

0

1,375
9


9,680,681
Asia
727107,563


131
Réunion
13,125

59

11,956

1,110
66
14,590
66
98,785
109,808
899,612
Africa
6915,2489


132
Haiti
12,536

250

9,828

2,458

1,090
22
54,379
4,730
11,495,844
North America
91745,983211


133
Belize
12,329

314

11,916

99
2
30,634
780
86,570
215,103
402,459
North America
331,2825


134
Burkina Faso
12,103

143

11,677

283

569
7


21,284,950
Africa
1,759148,846


135
Hong Kong
11,056

201

10,593

262
13
1,467
27
8,601,877
1,141,151
7,537,896
Asia
68237,5021


136
Andorra
10,976

112

10,564

300
17
141,904
1,448
193,595
2,502,909
77,348
Europe
76910


137
Lesotho
10,522

307

3,888

6,327

4,886
143
61,795
28,693
2,153,674
Africa
2057,01535


138
Guadeloupe
10,149

162

2,242

7,745
5
25,362
405
135,623
338,913
400,170
North America
392,4703


139
Congo
9,179

131

7,019

2,029

1,637
23
92,500
16,492
5,608,669
Africa
61142,81461


140
Suriname
8,959

175

8,450

334
3
15,180
297
41,415
70,175
590,166
South America
663,37214


141
Guyana
8,699

199

8,074

426
7
11,024
252
68,478
86,779
789,109
South America
913,96512


142
Bahamas
8,573

181

7,398

994
1
21,662
457
69,003
174,351
395,770
North America
462,1876


143
Mali
8,470

357

6,424

1,689

410
17
153,345
7,430
20,638,937
Africa
2,43757,812135


144
South Sudan
8,414

100

4,317

3,997
8
746
9
112,863
10,004
11,281,848
Africa
1,341112,818100


145
Aruba
8,009

75

7,725

209
11
74,800
700
107,331
1,002,419
107,072
North America
131,4281


146
Somalia
7,850

274

3,901

3,675

485
17


16,188,403
Africa
2,06259,082


147
Trinidad and Tobago
7,727

139

7,487

101
2
5,509
99
98,370
70,137
1,402,544
North America
18210,09014


148
Togo
7,323

88

6,069

1,166

871
10
241,306
28,699
8,408,208
Africa
1,14895,54835


149
Martinique
6,818

46

98

6,674
3
18,178
123
104,749
279,280
375,068
North America
558,1544


150
Nicaragua
6,489

174

4,225

2,090

972
26


6,677,473
North America
1,02938,376


151
Equatorial Guinea
6,210

93

5,690

427
24
4,332
65
99,474
69,388
1,433,585
Africa
23115,41514


152
Djibouti
6,110

63

5,926

121

6,124
63
116,919
117,196
997,634
Africa
16315,8359


153
Benin
6,071

75

4,963

1,033
35
492
6
504,305
40,885
12,334,788
Africa
2,032164,46424


154
Iceland
6,058

29

6,018

11
7
17,676
85
503,309
1,468,512
342,734
Europe
5711,8181


155
CAR
5,018

63

4,920

35
2
1,027
13
37,104
7,594
4,885,989
Africa
97477,555132


156
Gambia
4,759

152

4,143

464
8
1,933
62
44,076
17,904
2,461,860
Africa
51716,19656


157
Curaçao
4,751

22

4,659

70
1
28,874
134
51,868
315,221
164,545
North America
357,4793


158
Niger
4,740

172

4,250

318
23
191
7
78,967
3,186
24,787,266
Africa
5,229144,112314


159
Gibraltar
4,243

93

4,128

22
2
125,965
2,761
190,475
5,654,762
33,684
Europe
83620


160
Chad
4,089

140

3,572

377

244
8


16,739,501
Africa
4,094119,568


161
Channel Islands
4,041

86

3,948

7
1
23,099
492
380,165
2,173,116
174,940
Europe
432,0340


162
Sierra Leone
3,900

79

2,652

1,169

482
10
116,448
14,402
8,085,420
Africa
2,073102,34769


163
San Marino
3,867

75

3,361

431
7
113,806
2,207
44,026
1,295,683
33,979
Europe
94531


164
Saint Lucia
3,814

43

3,442

329
2
20,707
233
32,471
176,288
184,193
North America
484,2846


165
Comoros
3,580

144

3,369

67

4,059
163


881,977
Africa
2466,125


166
Guinea-Bissau
3,301

49

2,655

597
7
1,651
25
53,206
26,616
1,999,038
Africa
60640,79738


167
Barbados
3,186

37

2,651

498

11,077
129
128,291
446,056
287,612
North America
907,7732


168
Mongolia
3,076

2

2,415

659
7
928
0.6
1,855,597
559,984
3,313,660
Asia
1,0771,656,8302


169
Seychelles
2,928

13

2,582

333

29,649
132
5,200
52,654
98,757
Africa
347,59719


170
Eritrea
2,913

7

2,388

518

814
2
23,693
6,619
3,579,344
Africa
1,229511,335151


171
Liechtenstein
2,582

54

2,487

41
2
67,588
1,414
28,293
740,616
38,202
Europe
157071


172
Vietnam
2,488

35

1,920

533

25
0.4
1,997,072
20,393
97,927,471
Asia
39,3602,797,92849


173
New Zealand
2,389

26

2,295

68

478
5
1,763,008
352,454
5,002,100
Australia/Oceania
2,094192,3883


174
Yemen
2,375

645

1,435

295
23
78
21
17,404
575
30,264,675
Asia
12,74346,9221,739


175
Burundi
2,268

3

773

1,492

187
0.2
90,019
7,423
12,126,294
Africa
5,3474,042,098135


176
Turks and Caicos
2,161

14

1,976

171
5
55,314
358
17,163
439,311
39,068
North America
182,7912


177
Sint Maarten
2,066

27

2,022

17
2
47,821
625
21,103
488,461
43,203
North America
211,6002


178
Liberia
2,017

85

1,884

48
2
393
17
73,921
14,390
5,137,008
Africa
2,54760,43569


179
Monaco
1,997

26

1,770

201
8
50,648
659
51,953
1,317,634
39,429
Europe
201,5171


180
Sao Tome and Principe
1,898

30

1,497

371

8,554
135
11,592
52,244
221,882
Africa
1177,39619


181
St. Vincent Grenadines
1,645

8

949

688
2
14,796
72
36,649
329,643
111,178
North America
6813,8973


182
Saint Martin
1,571

12

1,399

160
7
40,171
307
22,204
567,761
39,108
North America
253,2592


183
Papua New Guinea
1,365

14

846

505

151
2
47,490
5,241
9,060,401
Australia/Oceania
6,638647,172191


184
Taiwan
960

9

928

23

40
0.4
175,846
7,374
23,845,858
Asia
24,8392,649,540136


185
Cambodia
932
+23


489
+5
443

55

500,000
29,631
16,874,167
Asia
18,10534


186
Bhutan
867

1

865

1

1,115
1
532,808
685,447
777,315
Asia
897777,3151


187
Antigua and Barbuda
803

21

327

455
40
8,154
213
13,976
141,926
98,474
North America
1234,6897


188
Bermuda
718

12

685

21

11,558
193
176,835
2,846,576
62,122
North America
875,1770


189
Diamond Princess
712

13

699

0










190
Faeroe Islands
658

1

657

0

13,432
20
232,631
4,748,734
48,988
Europe
7448,9880


191
St. Barth

In [6]:
data=[]
for i in tags:
    data.append(i.text)
data

['\n#\nCountry,Other\nTotalCases\nNewCases\nTotalDeaths\nNewDeaths\nTotalRecovered\nNewRecovered\nActiveCases\nSerious,Critical\nTot\xa0Cases/1M pop\nDeaths/1M pop\nTotalTests\nTests/\n1M pop\n\nPopulation\nContinent\n1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl\n',
 '\n\n\nNorth America\n\n33,890,918\n+7,521\n771,371\n+822\n23,706,426\n+5,319\n9,413,121\n20,461\n\n\n\n\n\nNorth America\n\n\n\n\n',
 '\n\n\nAsia\n\n25,312,988\n+430\n401,501\n+8\n23,765,863\n+411\n1,145,624\n21,968\n\n\n\n\n\nAsia\n\n\n\n\n',
 '\n\n\nSouth America\n\n18,329,295\n+969\n475,595\n+27\n16,566,888\n+606\n1,286,812\n19,066\n\n\n\n\n\nSouth America\n\n\n\n\n',
 '\n\n\nEurope\n\n34,664,874\n\n826,911\n\n24,282,703\n\n9,555,260\n25,776\n\n\n\n\n\nEurope\n\n\n\n\n',
 '\n\n\nAfrica\n\n3,966,393\n\n105,165\n\n3,527,350\n\n333,878\n2,474\n\n\n\n\n\nAfrica\n\n\n\n\n',
 '\n\n\nOceania\n\n51,391\n+14\n1,091\n\n34,313\n+3\n15,987\n2\n\n\n\n\n\nAustralia/Oceania\n\n\n\n\n',
 '\n\n\n\n\n721\n\n15\n\n706\n\n0\n0\n\n\n\n\n\n\n\n\n\n\n',
 '\n\nWorld\n116,216,580\n+8,934\n2,581,649\n+857\n91,884,249\n+6,339\n21,750,682\n89,747\n14,910\n331.2\n\n\n\nAll\n\n\n\n\n',
 '\n1\nUSA\n29,526,086\n\n533,636 \n\n20,093,442\n\n8,899,008\n13,934\n88,851\n1,606\n365,017,193\n1,098,425\n332,309,730 \nNorth America\n116231\n',
 '\n2\nIndia\n11,173,572\n\n157,584 \n\n10,838,021\n\n177,967\n8,944\n8,044\n113\n219,178,908\n157,782\n1,389,123,461 \nAsia\n1248,8156\n',
 '\n3\nBrazil\n10,796,506\n\n261,188 \n\n9,637,020\n\n898,298\n8,318\n50,551\n1,223\n28,600,000\n133,910\n213,576,312 \nSouth America\n208187\n',
 '\n4\nRussia\n4,290,135\n\n87,823 \n\n3,869,857\n\n332,455\n2,300\n29,389\n602\n112,100,000\n767,931\n145,976,706 \nEurope\n341,6621\n',
 '\n5\nUK\n4,201,358\n\n124,025 \n\n3,096,564\n\n980,769\n1,647\n61,670\n1,821\n93,148,314\n1,367,290\n68,126,222 \nEurope\n165491\n',
 '\n6\nFrance\n3,835,595\n\n87,835 \n\n262,690\n\n3,485,070\n3,633\n58,674\n1,344\n53,959,451\n825,435\n65,370,939 \nEurope\n177441\n',
 '\n7\nSpain\n3,142,358\n\n70,501 \n\n2,722,304\n\n349,553\n2,615\n67,192\n1,507\n39,313,189\n840,618\n46,767,004 \nEurope\n156631\n',
 '\n8\nItaly\n2,999,119\n\n98,974 \n\n2,453,706\n\n446,439\n2,475\n49,653\n1,639\n41,338,022\n684,384\n60,401,757 \nEurope\n206101\n',
 '\n9\nTurkey\n2,746,158\n\n28,839 \n\n2,601,137\n\n116,182\n1,220\n32,327\n339\n33,716,746\n396,907\n84,948,754 \nAsia\n312,9463\n',
 '\n10\nGermany\n2,484,306\n\n72,007 \n\n2,283,400\n\n128,899\n2,848\n29,588\n858\n45,114,160\n537,300\n83,964,573 \nEurope\n341,1662\n',
 '\n11\nColombia\n2,266,211\n\n60,189 \n\n2,164,438\n\n41,584\n2,240\n44,221\n1,174\n11,614,196\n226,631\n51,247,260 \nSouth America\n238514\n',
 '\n12\nArgentina\n2,133,963\n\n52,644 \n\n1,928,377\n\n152,942\n3,521\n46,926\n1,158\n7,617,966\n167,521\n45,474,610 \nSouth America\n218646\n',
 '\n13\nMexico\n2,112,508\n+7,521\n188,866 \n+822\n1,655,549\n+5,319\n268,093\n4,798\n16,270\n1,455\n5,555,699\n42,788\n129,842,915 \nNorth America\n6168723\n',
 '\n14\nPoland\n1,750,659\n\n44,649 \n\n1,448,619\n\n257,391\n1,650\n46,291\n1,181\n10,070,976\n266,297\n37,818,609 \nEurope\n228474\n',
 '\n15\nIran\n1,665,103\n\n60,431 \n\n1,420,958\n\n183,714\n3,760\n19,655\n713\n11,092,900\n130,945\n84,714,448 \nAsia\n511,4028\n',
 '\n16\nSouth Africa\n1,517,666\n\n50,462 \n\n1,436,010\n\n31,194\n546\n25,375\n844\n9,178,323\n153,457\n59,810,579 \nAfrica\n391,1857\n',
 '\n17\nUkraine\n1,374,762\n\n26,591 \n\n1,186,873\n\n161,298\n177\n31,563\n611\n7,021,993\n161,218\n43,555,898 \nEurope\n321,6386\n',
 '\n18\nIndonesia\n1,361,098\n\n36,897 \n\n1,176,356\n\n147,845\n\n4,941\n134\n11,004,843\n39,950\n275,466,894 \nAsia\n2027,46625\n',
 '\n19\nPeru\n1,349,847\n\n47,306 \n\n1,250,047\n\n52,494\n2,176\n40,560\n1,421\n7,757,176\n233,089\n33,279,921 \nSouth America\n257044\n',
 '\n20\nCzechia\n1,284,288\n\n21,128 \n\n1,104,592\n\n158,568\n1,708\n119,776\n1,970\n8,389,822\n782,459\n10,722,385 \nEurope\n85071\n',
 '\n21\nNetherlands\n1,105,544\n\n15,730 \n\nN/A\nN/A\nN/A\n549\n64,424\n917\n6,970,400\n406,190\n17,160,446 \nEurope\n161,0912\n',
 '\n22\nCanada\n878,391\n\n22,151 \n\n826,337\n\n29,903\n572\n23,137\n583\n24,763,481\n652,277\n37,964,686 \nNorth America\n431,7142\n',
 '\n23\nChile\n840,119\n\n20,838 \n\n793,819\n\n25,462\n1,711\n43,696\n1,084\n9,538,043\n496,087\n19,226,558 \nSouth America\n239232\n',
 '\n24\nRomania\n816,589\n\n20,684 \n\n749,673\n\n46,232\n1,070\n42,640\n1,080\n6,439,713\n336,264\n19,150,793 \nEurope\n239263\n',
 '\n25\nPortugal\n807,456\n\n16,458 \n\n727,053\n\n63,945\n399\n79,344\n1,617\n8,318,706\n817,434\n10,176,609 \nEurope\n136181\n',
 '\n26\nIsrael\n793,407\n\n5,822 \n\n746,228\n\n41,357\n702\n86,262\n633\n12,199,957\n1,326,430\n9,197,590 \nAsia\n121,5801\n',
 '\n27\nBelgium\n777,608\n\n22,169 \n\n52,863\n\n702,576\n426\n66,899\n1,907\n9,587,540\n824,833\n11,623,613 \nEurope\n155241\n',
 '\n28\nIraq\n713,994\n\n13,507 \n\n650,015\n\n50,472\n387\n17,489\n331\n7,008,505\n171,671\n40,825,159 \nAsia\n573,0236\n',
 '\n29\nSweden\n680,130\n\n12,977 \n\nN/A\nN/A\nN/A\n231\n67,063\n1,280\n6,139,911\n605,415\n10,141,664 \nEurope\n157822\n',
 '\n30\nPakistan\n585,435\n\n13,076 \n\n555,242\n\n17,117\n1,559\n2,616\n58\n9,097,413\n40,657\n223,760,893 \nAsia\n38217,11225\n',
 '\n31\nPhilippines\n584,667\n\n12,404 \n\n535,037\n\n37,226\n785\n5,288\n112\n8,875,386\n80,277\n110,559,647 \nAsia\n1898,91312\n',
 '\n32\nSwitzerland\n561,068\n\n10,022 \n\n516,798\n\n34,248\n161\n64,511\n1,152\n5,167,034\n594,102\n8,697,214 \nEurope\n168682\n',
 '\n33\nBangladesh\n548,549\n\n8,435 \n\n500,468\n\n39,646\n\n3,309\n51\n4,105,321\n24,762\n165,792,097 \nAsia\n30219,65540\n',
 '\n34\nMorocco\n485,147\n\n8,669 \n\n470,933\n\n5,545\n241\n13,040\n233\n5,695,763\n153,094\n37,204,312 \nAfrica\n774,2927\n',
 '\n35\nSerbia\n474,807\n\n4,508 \n\n400,347\n\n69,952\n173\n54,491\n517\n3,002,480\n344,575\n8,713,566 \nEurope\n181,9333\n',
 '\n36\nAustria\n467,646\n\n8,652 \n\n437,202\n\n21,792\n302\n51,725\n957\n5,557,591\n614,709\n9,041,006 \nEurope\n191,0452\n',
 '\n37\nHungary\n446,178\n\n15,476 \n\n328,136\n\n102,566\n639\n46,266\n1,605\n3,749,907\n388,842\n9,643,770 \nEurope\n226233\n',
 '\n38\nJapan\n435,548\n\n8,052 \n\n414,774\n\n12,722\n398\n3,451\n64\n8,435,308\n66,833\n126,214,686 \nAsia\n29015,67515\n',
 '\n39\nJordan\n413,350\n\n4,833 \n\n356,648\n\n51,869\n377\n40,244\n471\n4,761,823\n463,609\n10,271,210 \nAsia\n252,1252\n',
 '\n40\nUAE\n402,205\n\n1,286 \n\n387,278\n\n13,641\n\n40,339\n129\n31,520,191\n3,161,304\n9,970,628 \nAsia\n257,7530\n',
 '\n41\nLebanon\n386,868\n\n4,919 \n\n300,923\n\n81,026\n885\n56,852\n723\n3,095,306\n454,873\n6,804,767 \nAsia\n181,3832\n',
 '\n42\nSaudi Arabia\n378,708\n\n6,514 \n\n369,613\n\n2,581\n503\n10,766\n185\n13,829,692\n393,143\n35,177,214 \nAsia\n935,4003\n',
 '\n43\nPanama\n343,281\n\n5,895 \n\n329,709\n\n7,677\n195\n78,729\n1,352\n1,940,572\n445,057\n4,360,282 \nNorth America\n137402\n',
 '\n44\nSlovakia\n317,159\n\n7,560 \n\n255,300\n\n54,299\n683\n58,073\n1,384\n2,088,725\n382,450\n5,461,427 \nEurope\n177223\n',
 '\n45\nMalaysia\n307,943\n\n1,153 \n\n283,629\n\n23,161\n193\n9,433\n35\n6,407,625\n196,286\n32,644,300 \nAsia\n10628,3125\n',
 '\n46\nBelarus\n291,621\n\n2,011 \n\n282,039\n\n7,571\n\n30,868\n213\n4,951,979\n524,173\n9,447,224 \nEurope\n324,6982\n',
 '\n47\nEcuador\n289,735\n\n15,959 \n\n247,898\n\n25,878\n510\n16,257\n895\n1,025,254\n57,525\n17,822,631 \nSouth America\n621,11717\n',
 '\n48\nNepal\n274,488\n\n2,778 \n\n270,683\n\n1,027\n\n9,309\n94\n2,179,047\n73,897\n29,487,561 \nAsia\n10710,61514\n',
 '\n49\nGeorgia\n271,872\n\n3,553 \n\n266,081\n\n2,238\n\n68,241\n892\n2,788,971\n700,044\n3,983,992 \nAsia\n151,1211\n',
 '\n50\nBulgaria\n255,381\n\n10,506 \n\n210,638\n\n34,237\n440\n36,942\n1,520\n1,714,278\n247,978\n6,913,014 \nEurope\n276584\n',
 '\n51\nBolivia\n252,360\n+969\n11,761 \n+27\n195,705\n+606\n44,894\n71\n21,423\n998\n747,057\n63,418\n11,779,836 \nSouth America\n471,00216\n',
 '\n52\nCroatia\n244,872\n\n5,564 \n\n235,750\n\n3,558\n69\n59,898\n1,361\n1,368,448\n334,737\n4,088,128 \nEurope\n177353\n',
 '\n53\nDominican Republic\n241,392\n\n3,139 \n\n194,653\n\n43,600\n192\n22,103\n287\n1,219,587\n111,673\n10,921,018 \nNorth America\n453,4799\n',
 '\n54\nAzerbaijan\n235,647\n\n3,232 \n\n229,267\n\n3,148\n\n23,101\n317\n2,627,991\n257,630\n10,200,626 \nAsia\n433,1564\n',
 '\n55\nTunisia\n235,643\n\n8,106 \n\n200,984\n\n26,553\n263\n19,799\n681\n993,230\n83,453\n11,901,712 \nAfrica\n511,46812\n',
 '\n56\nIreland\n221,649\n\n4,396 \n\n23,364\n\n193,889\n103\n44,554\n884\n3,590,079\n721,648\n4,974,833 \nEurope\n221,1321\n',
 '\n57\nKazakhstan\n215,610\n\n2,540 \n\n199,600\n\n13,470\n221\n11,391\n134\n7,419,449\n391,993\n18,927,501 \nAsia\n887,4523\n',
 '\n58\nDenmark\n213,318\n\n2,374 \n\n203,934\n\n7,010\n18\n36,741\n409\n17,602,056\n3,031,726\n5,805,953 \nEurope\n272,4460\n',
 '\n59\nCosta Rica\n206,293\n\n2,829 \n\n186,093\n\n17,371\n133\n40,249\n552\n700,259\n136,625\n5,125,394 \nNorth America\n251,8127\n',
 '\n60\nLithuania\n200,884\n\n3,294 \n\n186,737\n\n10,853\n117\n74,498\n1,222\n2,150,037\n797,346\n2,696,493 \nEurope\n138191\n',
 '\n61\nGreece\n199,496\n\n6,632 \n\n172,321\n\n20,543\n449\n19,203\n638\n5,425,308\n522,236\n10,388,605 \nEurope\n521,5662\n',
 '\n62\nKuwait\n196,497\n\n1,105 \n\n183,321\n\n12,071\n167\n45,560\n256\n1,822,389\n422,542\n4,312,914 \nAsia\n223,9032\n',
 '\n63\nSlovenia\n193,285\n\n3,878 \n\n178,510\n\n10,897\n86\n92,964\n1,865\n930,169\n447,384\n2,079,131 \nEurope\n115362\n',
 '\n64\nPalestine\n191,203\n\n2,091 \n\n171,318\n\n17,794\n135\n36,908\n404\n1,202,259\n232,071\n5,180,562 \nAsia\n272,4784\n',
 '\n65\nMoldova\n191,197\n\n4,049 \n\n168,801\n\n18,347\n311\n47,471\n1,005\n733,323\n182,073\n4,027,626 \nEurope\n219955\n',
 '\n66\nEgypt\n184,755\n\n10,871 \n\n142,610\n\n31,274\n90\n1,783\n105\n1,000,000\n9,650\n103,625,644 \nAfrica\n5619,532104\n',
 '\n67\nGuatemala\n176,876\n\n6,435 \n\n163,544\n\n6,897\n5\n9,752\n355\n935,380\n51,572\n18,137,320 \nNorth America\n1032,81919\n',
 '\n68\nArmenia\n173,307\n\n3,208 \n\n164,085\n\n6,014\n\n58,412\n1,081\n742,038\n250,099\n2,966,980 \nAsia\n179254\n',
 '\n69\nHonduras\n172,100\n\n4,214 \n\n67,239\n\n100,647\n403\n17,193\n421\n454,905\n45,444\n10,010,158 \nNorth America\n582,37522\n',
 '\n70\nQatar\n165,546\n\n260 \n\n155,070\n\n10,216\n111\n58,959\n93\n1,563,932\n556,995\n2,807,805 \nAsia\n1710,7992\n',
 '\n71\nParaguay\n164,310\n\n3,256 \n\n137,368\n\n23,686\n293\n22,848\n453\n765,862\n106,498\n7,191,352 \nSouth America\n442,2099\n',
 '\n72\nEthiopia\n162,954\n\n2,394 \n\n137,203\n\n23,357\n392\n1,394\n20\n2,158,296\n18,469\n116,862,573 \nAfrica\n71748,81554\n',
 '\n73\nNigeria\n157,671\n\n1,951 \n\n136,335\n\n19,385\n10\n752\n9\n1,544,008\n7,368\n209,546,665 \nAfrica\n1,329107,405136\n',
 '\n74\nOman\n142,896\n\n1,583 \n\n133,491\n\n7,822\n80\n27,516\n305\n1,550,000\n298,467\n5,193,202 \nAsia\n363,2813\n',
 '\n75\nMyanmar\n142,000\n\n3,200 \n\n131,571\n\n7,229\n\n2,598\n59\n2,496,367\n45,675\n54,655,331 \nAsia\n38517,08022\n',
 '\n76\nVenezuela\n140,960\n\n1,364 \n\n133,034\n\n6,562\n131\n4,967\n48\n2,920,112\n102,888\n28,381,471 \nSouth America\n20120,80810\n',
 '\n77\nLibya\n136,587\n\n2,233 \n\n123,777\n\n10,577\n\n19,698\n322\n741,874\n106,991\n6,933,974 \nAfrica\n513,1059\n',
 '\n78\nBosnia and Herzegovina\n134,892\n\n5,200 \n\n117,643\n\n12,049\n\n41,289\n1,592\n678,280\n207,615\n3,267,003 \nEurope\n246285\n',
 '\n79\nBahrain\n124,857\n\n462 \n\n117,656\n\n6,739\n60\n71,724\n265\n3,151,398\n1,810,317\n1,740,799 \nAsia\n143,7681\n',
 '\n80\nAlgeria\n113,761\n\n3,002 \n\n78,672\n\n32,087\n23\n2,563\n68\n\n\n44,381,005 \nAfrica\n39014,784\n',
 '\n81\nAlbania\n110,521\n\n1,876 \n\n72,853\n\n35,792\n46\n38,433\n652\n471,618\n164,003\n2,875,674 \nEurope\n261,5336\n',
 '\n82\nKenya\n107,329\n\n1,870 \n\n87,099\n\n18,360\n61\n1,967\n34\n1,317,617\n24,149\n54,562,325 \nAfrica\n50829,17841\n',
 '\n83\nNorth Macedonia\n105,269\n\n3,165 \n\n93,942\n\n8,162\n124\n50,530\n1,519\n533,505\n256,085\n2,083,316 \nEurope\n206584\n',
 '\n84\nS. Korea\n91,638\n+398\n1,627 \n+8\n82,560\n+398\n7,451\n135\n1,786\n32\n6,789,011\n132,342\n51,298,966 \nAsia\n56031,5308\n',
 '\n85\nLatvia\n88,668\n\n1,666 \n\n77,830\n\n9,172\n74\n47,364\n890\n1,547,619\n826,697\n1,872,052 \nEurope\n211,1241\n',
 '\n86\nKyrgyzstan\n86,410\n\n1,468 \n\n83,375\n\n1,567\n16\n13,100\n223\n756,425\n114,674\n6,596,295 \nAsia\n764,4939\n',
 '\n87\nGhana\n85,239\n\n629 \n\n79,465\n\n5,145\n101\n2,705\n20\n910,673\n28,904\n31,506,390 \nAfrica\n37050,09035\n',
 '\n88\nSri Lanka\n84,610\n\n489 \n\n80,836\n\n3,285\n\n3,940\n23\n2,122,696\n98,851\n21,473,757 \nAsia\n25443,91410\n',
 '\n89\nZambia\n80,687\n\n1,109 \n\n76,498\n\n3,080\n212\n4,309\n59\n1,113,622\n59,467\n18,726,681 \nAfrica\n23216,88617\n',
 '\n90\nUzbekistan\n80,035\n\n622 \n\n78,587\n\n826\n27\n2,368\n18\n1,377,915\n40,773\n33,794,452 \nAsia\n42254,33225\n',
 '\n91\nMontenegro\n78,060\n\n1,039 \n\n68,177\n\n8,844\n68\n124,276\n1,654\n287,262\n457,336\n628,120 \nEurope\n86052\n',
 '\n92\nNorway\n73,493\n\n632 \n\n66,014\n\n6,847\n18\n13,486\n116\n3,910,562\n717,566\n5,449,761 \nEurope\n748,6231\n',
 '\n93\nEstonia\n70,610\n\n623 \n\n53,360\n\n16,627\n44\n53,205\n469\n960,700\n723,889\n1,327,137 \nEurope\n192,1301\n',
 '\n94\nMozambique\n61,170\n\n674 \n\n44,276\n\n16,220\n\n1,921\n21\n433,264\n13,608\n31,838,340 \nAfrica\n52047,23873\n',
 '\n95\nUruguay\n60,945\n\n631 \n\n52,612\n\n7,702\n79\n17,504\n181\n1,043,679\n299,749\n3,481,846 \nSouth America\n575,5183\n',
 '\n96\nEl Salvador\n60,800\n\n1,887 \n\n56,807\n\n2,106\n56\n9,342\n290\n776,696\n119,340\n6,508,253 \nNorth America\n1073,4498\n',
 '\n97\nFinland\n60,200\n\n764 \n\n46,000\n\n13,436\n39\n10,854\n138\n3,407,853\n614,412\n5,546,528 \nEurope\n927,2602\n',
 '\n98\nSingapore\n59,998\n\n29 \n\n59,857\n\n112\n1\n10,201\n5\n7,543,963\n1,282,704\n5,881,296 \nAsia\n98202,8031\n',
 '\n99\nLuxembourg\n56,110\n\n647 \n\n52,445\n\n3,018\n22\n88,669\n1,022\n2,155,640\n3,406,511\n632,800 \nEurope\n119780\n',
 '\n100\nAfghanistan\n55,933\n\n2,449 \n\n49,362\n\n4,122\n1,073\n1,416\n62\n305,242\n7,725\n39,513,703 \nAsia\n70616,135129\n',
 '\n101\nCuba\n53,308\n\n336 \n\n48,341\n\n4,631\n63\n4,708\n30\n2,464,521\n217,676\n11,321,947 \nNorth America\n21233,6965\n',
 '\n102\nUganda\n40,426\n\n334 \n\n15,052\n\n25,040\n\n866\n7\n887,701\n19,008\n46,700,691 \nAfrica\n1,155139,82253\n',
 '\n103\nNamibia\n39,466\n\n436 \n\n37,043\n\n1,987\n21\n15,346\n170\n307,936\n119,740\n2,571,701 \nAfrica\n655,8988\n',
 '\n104\nZimbabwe\n36,223\n\n1,483 \n\n33,632\n\n1,108\n41\n2,414\n99\n345,679\n23,033\n15,007,997 \nAfrica\n41410,12043\n',
 '\n105\nCyprus\n36,004\n\n232 \n\n2,057\n\n33,715\n22\n29,675\n191\n2,117,939\n1,745,639\n1,213,274 \nAsia\n345,2301\n',
 '\n106\nCameroon\n35,714\n\n551 \n\n32,594\n\n2,569\n53\n1,323\n20\n905,000\n33,535\n26,986,485 \nAfrica\n75648,97730\n',
 '\n107\nSenegal\n35,247\n\n898 \n\n29,889\n\n4,460\n48\n2,069\n53\n396,058\n23,246\n17,037,916 \nAfrica\n48318,97343\n',
 '\n108\nIvory Coast\n33,976\n\n196 \n\n32,245\n\n1,535\n\n1,267\n7\n432,695\n16,137\n26,813,868 \nAfrica\n789136,80562\n',
 '\n109\nMalawi\n32,283\n\n1,058 \n\n20,582\n\n10,643\n4\n1,659\n54\n201,422\n10,351\n19,459,402 \nAfrica\n60318,39397\n',
 '\n110\nBotswana\n31,746\n\n359 \n\n26,760\n\n4,627\n1\n13,320\n151\n825,247\n346,252\n2,383,369 \nAfrica\n756,6393\n',
 '\n111\nAustralia\n29,021\n+14\n909 \n\n26,189\n+3\n1,923\n\n1,129\n35\n14,558,706\n566,518\n25,698,566 \nAustralia/Oceania\n88628,2712\n',
 '\n112\nSudan\n28,545\n\n1,895 \n\n23,084\n\n3,566\n\n641\n43\n\n\n44,532,525 \nAfrica\n1,56023,500\n',
 '\n113\nDRC\n26,340\n\n711 \n\n20,601\n\n5,028\n\n288\n8\n\n\n91,371,512 \nAfrica\n3,469128,511\n',
 '\n114\nThailand\n26,162\n\n85 \n\n25,562\n\n515\n1\n374\n1\n1,217,873\n17,419\n69,918,107 \nAsia\n2,673822,56657\n',
 '\n115\nJamaica\n24,444\n\n436 \n\n13,869\n\n10,139\n27\n8,231\n147\n220,388\n74,208\n2,969,877 \nNorth America\n1216,81213\n',
 '\n116\nMalta\n23,588\n\n325 \n\n20,135\n\n3,128\n18\n53,326\n735\n713,482\n1,612,987\n442,336 \nEurope\n191,3611\n',
 '\n117\nAngola\n20,981\n\n511 \n\n19,553\n\n917\n10\n625\n15\n193,425\n5,766\n33,545,658 \nAfrica\n1,59965,647173\n',
 '\n118\nMaldives\n20,447\n\n64 \n\n17,712\n\n2,671\n162\n37,386\n117\n541,164\n989,481\n546,917 \nAsia\n278,5461\n',
 '\n119\nMadagascar\n19,831\n\n297 \n\n19,296\n\n238\n23\n704\n11\n119,608\n4,247\n28,165,495 \nAfrica\n1,42094,833235\n',
 '\n120\nRwanda\n19,334\n\n266 \n\n17,682\n\n1,386\n11\n1,468\n20\n1,025,213\n77,866\n13,166,323 \nAfrica\n68149,49713\n',
 '\n121\nFrench Polynesia\n18,459\n\n140 \n\n4,842\n\n13,477\n2\n65,457\n496\n26,355\n93,457\n282,002 \nAustralia/Oceania\n152,01411\n',
 '\n122\nMayotte\n18,054\n\n112 \n\n2,964\n\n14,978\n25\n65,128\n404\n130,738\n471,628\n277,206 \nAfrica\n152,4752\n',
 '\n123\nMauritania\n17,267\n\n442 \n\n16,633\n\n192\n14\n3,650\n93\n177,070\n37,427\n4,731,092 \nAfrica\n27410,70427\n',
 '\n124\nEswatini\n17,129\n\n654 \n\n15,039\n\n1,436\n36\n14,662\n560\n154,260\n132,045\n1,168,236 \nAfrica\n681,7868\n',
 '\n125\nFrench Guiana\n16,627\n\n85 \n\n9,995\n\n6,547\n6\n54,723\n280\n149,894\n493,330\n303,841 \nSouth America\n183,5752\n',
 '\n126\nGuinea\n16,420\n\n93 \n\n15,091\n\n1,236\n24\n1,228\n7\n144,351\n10,797\n13,370,037 \nAfrica\n814143,76493\n',
 '\n127\nSyria\n15,815\n\n1,050 \n\n10,123\n\n4,642\n\n889\n59\n\n\n17,784,235 \nAsia\n1,12516,937\n',
 '\n128\nCabo Verde\n15,621\n\n152 \n\n14,959\n\n510\n23\n27,892\n271\n122,430\n218,608\n560,044 \nAfrica\n363,6855\n',
 '\n129\nGabon\n15,254\n\n88 \n\n13,495\n\n1,671\n19\n6,747\n39\n539,866\n238,796\n2,260,779 \nAfrica\n14825,6914\n',
 '\n130\nTajikistan\n13,308\n\n90 \n\n13,218\n\n0\n\n1,375\n9\n\n\n9,680,681 \nAsia\n727107,563\n',
 '\n131\nRéunion\n13,125\n\n59 \n\n11,956\n\n1,110\n66\n14,590\n66\n98,785\n109,808\n899,612 \nAfrica\n6915,2489\n',
 '\n132\nHaiti\n12,536\n\n250 \n\n9,828\n\n2,458\n\n1,090\n22\n54,379\n4,730\n11,495,844 \nNorth America\n91745,983211\n',
 '\n133\nBelize\n12,329\n\n314 \n\n11,916\n\n99\n2\n30,634\n780\n86,570\n215,103\n402,459 \nNorth America\n331,2825\n',
 '\n134\nBurkina Faso\n12,103\n\n143 \n\n11,677\n\n283\n\n569\n7\n\n\n21,284,950 \nAfrica\n1,759148,846\n',
 '\n135\nHong Kong\n11,056\n\n201 \n\n10,593\n\n262\n13\n1,467\n27\n8,601,877\n1,141,151\n7,537,896 \nAsia\n68237,5021\n',
 '\n136\nAndorra\n10,976\n\n112 \n\n10,564\n\n300\n17\n141,904\n1,448\n193,595\n2,502,909\n77,348 \nEurope\n76910\n',
 '\n137\nLesotho\n10,522\n\n307 \n\n3,888\n\n6,327\n\n4,886\n143\n61,795\n28,693\n2,153,674 \nAfrica\n2057,01535\n',
 '\n138\nGuadeloupe\n10,149\n\n162  \n\n2,242\n\n7,745\n5\n25,362\n405\n135,623\n338,913\n400,170 \nNorth America\n392,4703\n',
 '\n139\nCongo\n9,179\n\n131 \n\n7,019\n\n2,029\n\n1,637\n23\n92,500\n16,492\n5,608,669 \nAfrica\n61142,81461\n',
 '\n140\nSuriname\n8,959\n\n175 \n\n8,450\n\n334\n3\n15,180\n297\n41,415\n70,175\n590,166 \nSouth America\n663,37214\n',
 '\n141\nGuyana\n8,699\n\n199 \n\n8,074\n\n426\n7\n11,024\n252\n68,478\n86,779\n789,109 \nSouth America\n913,96512\n',
 '\n142\nBahamas\n8,573\n\n181 \n\n7,398\n\n994\n1\n21,662\n457\n69,003\n174,351\n395,770 \nNorth America\n462,1876\n',
 '\n143\nMali\n8,470\n\n357 \n\n6,424\n\n1,689\n\n410\n17\n153,345\n7,430\n20,638,937 \nAfrica\n2,43757,812135\n',
 '\n144\nSouth Sudan\n8,414\n\n100 \n\n4,317\n\n3,997\n8\n746\n9\n112,863\n10,004\n11,281,848 \nAfrica\n1,341112,818100\n',
 '\n145\nAruba\n8,009\n\n75 \n\n7,725\n\n209\n11\n74,800\n700\n107,331\n1,002,419\n107,072 \nNorth America\n131,4281\n',
 '\n146\nSomalia\n7,850\n\n274 \n\n3,901\n\n3,675\n\n485\n17\n\n\n16,188,403 \nAfrica\n2,06259,082\n',
 '\n147\nTrinidad and Tobago\n7,727\n\n139 \n\n7,487\n\n101\n2\n5,509\n99\n98,370\n70,137\n1,402,544 \nNorth America\n18210,09014\n',
 '\n148\nTogo\n7,323\n\n88 \n\n6,069\n\n1,166\n\n871\n10\n241,306\n28,699\n8,408,208 \nAfrica\n1,14895,54835\n',

In [7]:
datas=data[0:25]
print(datas)

['\n#\nCountry,Other\nTotalCases\nNewCases\nTotalDeaths\nNewDeaths\nTotalRecovered\nNewRecovered\nActiveCases\nSerious,Critical\nTot\xa0Cases/1M pop\nDeaths/1M pop\nTotalTests\nTests/\n1M pop\n\nPopulation\nContinent\n1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl\n', '\n\n\nNorth America\n\n33,890,918\n+7,521\n771,371\n+822\n23,706,426\n+5,319\n9,413,121\n20,461\n\n\n\n\n\nNorth America\n\n\n\n\n', '\n\n\nAsia\n\n25,312,988\n+430\n401,501\n+8\n23,765,863\n+411\n1,145,624\n21,968\n\n\n\n\n\nAsia\n\n\n\n\n', '\n\n\nSouth America\n\n18,329,295\n+969\n475,595\n+27\n16,566,888\n+606\n1,286,812\n19,066\n\n\n\n\n\nSouth America\n\n\n\n\n', '\n\n\nEurope\n\n34,664,874\n\n826,911\n\n24,282,703\n\n9,555,260\n25,776\n\n\n\n\n\nEurope\n\n\n\n\n', '\n\n\nAfrica\n\n3,966,393\n\n105,165\n\n3,527,350\n\n333,878\n2,474\n\n\n\n\n\nAfrica\n\n\n\n\n', '\n\n\nOceania\n\n51,391\n+14\n1,091\n\n34,313\n+3\n15,987\n2\n\n\n\n\n\nAustralia/Oceania\n\n\n\n\n', '\n\n\n\n\n721\n\n15\n\n706\n\n0\n0\n\n\n\n\n\n\n\n\n\n\n', '\n\nWorld\n116,216,580\n+8,934\n2,581,649\n+857\n91,884,249\n+6,339\n21,750,682\n89,747\n14,910\n331.2\n\n\n\nAll\n\n\n\n\n', '\n1\nUSA\n29,526,086\n\n533,636 \n\n20,093,442\n\n8,899,008\n13,934\n88,851\n1,606\n365,017,193\n1,098,425\n332,309,730 \nNorth America\n116231\n', '\n2\nIndia\n11,173,572\n\n157,584 \n\n10,838,021\n\n177,967\n8,944\n8,044\n113\n219,178,908\n157,782\n1,389,123,461 \nAsia\n1248,8156\n', '\n3\nBrazil\n10,796,506\n\n261,188 \n\n9,637,020\n\n898,298\n8,318\n50,551\n1,223\n28,600,000\n133,910\n213,576,312 \nSouth America\n208187\n', '\n4\nRussia\n4,290,135\n\n87,823 \n\n3,869,857\n\n332,455\n2,300\n29,389\n602\n112,100,000\n767,931\n145,976,706 \nEurope\n341,6621\n', '\n5\nUK\n4,201,358\n\n124,025 \n\n3,096,564\n\n980,769\n1,647\n61,670\n1,821\n93,148,314\n1,367,290\n68,126,222 \nEurope\n165491\n', '\n6\nFrance\n3,835,595\n\n87,835 \n\n262,690\n\n3,485,070\n3,633\n58,674\n1,344\n53,959,451\n825,435\n65,370,939 \nEurope\n177441\n', '\n7\nSpain\n3,142,358\n\n70,501 \n\n2,722,304\n\n349,553\n2,615\n67,192\n1,507\n39,313,189\n840,618\n46,767,004 \nEurope\n156631\n', '\n8\nItaly\n2,999,119\n\n98,974 \n\n2,453,706\n\n446,439\n2,475\n49,653\n1,639\n41,338,022\n684,384\n60,401,757 \nEurope\n206101\n', '\n9\nTurkey\n2,746,158\n\n28,839 \n\n2,601,137\n\n116,182\n1,220\n32,327\n339\n33,716,746\n396,907\n84,948,754 \nAsia\n312,9463\n', '\n10\nGermany\n2,484,306\n\n72,007 \n\n2,283,400\n\n128,899\n2,848\n29,588\n858\n45,114,160\n537,300\n83,964,573 \nEurope\n341,1662\n', '\n11\nColombia\n2,266,211\n\n60,189 \n\n2,164,438\n\n41,584\n2,240\n44,221\n1,174\n11,614,196\n226,631\n51,247,260 \nSouth America\n238514\n', '\n12\nArgentina\n2,133,963\n\n52,644 \n\n1,928,377\n\n152,942\n3,521\n46,926\n1,158\n7,617,966\n167,521\n45,474,610 \nSouth America\n218646\n', '\n13\nMexico\n2,112,508\n+7,521\n188,866 \n+822\n1,655,549\n+5,319\n268,093\n4,798\n16,270\n1,455\n5,555,699\n42,788\n129,842,915 \nNorth America\n6168723\n', '\n14\nPoland\n1,750,659\n\n44,649 \n\n1,448,619\n\n257,391\n1,650\n46,291\n1,181\n10,070,976\n266,297\n37,818,609 \nEurope\n228474\n', '\n15\nIran\n1,665,103\n\n60,431 \n\n1,420,958\n\n183,714\n3,760\n19,655\n713\n11,092,900\n130,945\n84,714,448 \nAsia\n511,4028\n', '\n16\nSouth Africa\n1,517,666\n\n50,462 \n\n1,436,010\n\n31,194\n546\n25,375\n844\n9,178,323\n153,457\n59,810,579 \nAfrica\n391,1857\n']

In [8]:
final_output=[]
for i in datas:
    a=i.split('\n')[0:11]
    final_output.append(a)
final_output

[['',
  '#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical'],
 ['',
  '',
  '',
  'North America',
  '',
  '33,890,918',
  '+7,521',
  '771,371',
  '+822',
  '23,706,426',
  '+5,319'],
 ['',
  '',
  '',
  'Asia',
  '',
  '25,312,988',
  '+430',
  '401,501',
  '+8',
  '23,765,863',
  '+411'],
 ['',
  '',
  '',
  'South America',
  '',
  '18,329,295',
  '+969',
  '475,595',
  '+27',
  '16,566,888',
  '+606'],
 ['', '', '', 'Europe', '', '34,664,874', '', '826,911', '', '24,282,703', ''],
 ['', '', '', 'Africa', '', '3,966,393', '', '105,165', '', '3,527,350', ''],
 ['', '', '', 'Oceania', '', '51,391', '+14', '1,091', '', '34,313', '+3'],
 ['', '', '', '', '', '721', '', '15', '', '706', ''],
 ['',
  '',
  'World',
  '116,216,580',
  '+8,934',
  '2,581,649',
  '+857',
  '91,884,249',
  '+6,339',
  '21,750,682',
  '89,747'],
 ['',
  '1',
  'USA',
  '29,526,086',
  '',
  '533,636 ',
  '',
  '20,093,442',
  '',
  '8,899,008',
  '13,934'],
 ['',
  '2',
  'India',
  '11,173,572',
  '',
  '157,584 ',
  '',
  '10,838,021',
  '',
  '177,967',
  '8,944'],
 ['',
  '3',
  'Brazil',
  '10,796,506',
  '',
  '261,188 ',
  '',
  '9,637,020',
  '',
  '898,298',
  '8,318'],
 ['',
  '4',
  'Russia',
  '4,290,135',
  '',
  '87,823 ',
  '',
  '3,869,857',
  '',
  '332,455',
  '2,300'],
 ['',
  '5',
  'UK',
  '4,201,358',
  '',
  '124,025 ',
  '',
  '3,096,564',
  '',
  '980,769',
  '1,647'],
 ['',
  '6',
  'France',
  '3,835,595',
  '',
  '87,835 ',
  '',
  '262,690',
  '',
  '3,485,070',
  '3,633'],
 ['',
  '7',
  'Spain',
  '3,142,358',
  '',
  '70,501 ',
  '',
  '2,722,304',
  '',
  '349,553',
  '2,615'],
 ['',
  '8',
  'Italy',
  '2,999,119',
  '',
  '98,974 ',
  '',
  '2,453,706',
  '',
  '446,439',
  '2,475'],
 ['',
  '9',
  'Turkey',
  '2,746,158',
  '',
  '28,839 ',
  '',
  '2,601,137',
  '',
  '116,182',
  '1,220'],
 ['',
  '10',
  'Germany',
  '2,484,306',
  '',
  '72,007 ',
  '',
  '2,283,400',
  '',
  '128,899',
  '2,848'],
 ['',
  '11',
  'Colombia',
  '2,266,211',
  '',
  '60,189 ',
  '',
  '2,164,438',
  '',
  '41,584',
  '2,240'],
 ['',
  '12',
  'Argentina',
  '2,133,963',
  '',
  '52,644 ',
  '',
  '1,928,377',
  '',
  '152,942',
  '3,521'],
 ['',
  '13',
  'Mexico',
  '2,112,508',
  '+7,521',
  '188,866 ',
  '+822',
  '1,655,549',
  '+5,319',
  '268,093',
  '4,798'],
 ['',
  '14',
  'Poland',
  '1,750,659',
  '',
  '44,649 ',
  '',
  '1,448,619',
  '',
  '257,391',
  '1,650'],
 ['',
  '15',
  'Iran',
  '1,665,103',
  '',
  '60,431 ',
  '',
  '1,420,958',
  '',
  '183,714',
  '3,760'],
 ['',
  '16',
  'South Africa',
  '1,517,666',
  '',
  '50,462 ',
  '',
  '1,436,010',
  '',
  '31,194',
  '546']]

In [9]:
import csv
with open('world_meter.csv', 'a') as f:
    x = csv.writer(f)
    for i in final_output:
        x.writerow(i)
f.close()

In [10]:
import pandas as pd
df=pd.read_csv('world_meter.csv')
df

,Unnamed: 0,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical"
0,NaN,NaN,NaN,North America,NaN,"33,890,918","+7,521","771,371",+822,"23,706,426","+5,319"
1,NaN,NaN,NaN,Asia,NaN,"25,312,988",+430,"401,501",+8,"23,765,863",+411
2,NaN,NaN,NaN,South America,NaN,"18,329,295",+969,"475,595",+27,"16,566,888",+606
3,NaN,NaN,NaN,Europe,NaN,"34,664,874",NaN,"826,911",NaN,"24,282,703",NaN
4,NaN,NaN,NaN,Africa,NaN,"3,966,393",NaN,"105,165",NaN,"3,527,350",NaN
5,NaN,NaN,NaN,Oceania,NaN,"51,391",+14,"1,091",NaN,"34,313",+3
6,NaN,NaN,NaN,NaN,NaN,721,NaN,15,NaN,706,NaN
7,NaN,NaN,World,"116,216,580","+8,934","2,581,649",+857,"91,884,249","+6,339","21,750,682","89,747"
8,NaN,1.0,USA,"29,526,086",NaN,"533,636",NaN,"20,093,442",NaN,"8,899,008","13,934"
9,NaN,2.0,India,"11,173,572",NaN,"157,584",NaN,"10,838,021",NaN,"177,967","8,944"
10,NaN,3.0,Brazil,"10,796,506",NaN,"261,188",NaN,"9,637,020",NaN,"898,298","8,318"
11,NaN,4.0,Russia,"4,290,135",NaN,"87,823",NaN,"3,869,857",NaN,"332,455","2,300"
12,NaN,5.0,UK,"4,201,358",NaN,"124,025",NaN,"3,096,564",NaN,"980,769","1,647"
13,NaN,6.0,France,"3,835,595",NaN,"87,835",NaN,"262,690",NaN,"3,485,070","3,633"
14,NaN,7.0,Spain,"3,142,358",NaN,"70,501",NaN,"2,722,304",NaN,"349,553","2,615"
15,NaN,8.0,Italy,"2,999,119",NaN,"98,974",NaN,"2,453,706",NaN,"446,439","2,475"
16,NaN,9.0,Turkey,"2,746,158",NaN,"28,839",NaN,"2,601,137",NaN,"116,182","1,220"
17,NaN,10.0,Germany,"2,484,306",NaN,"72,007",NaN,"2,283,400",NaN,"128,899","2,848"
18,NaN,11.0,Colombia,"2,266,211",NaN,"60,189",NaN,"2,164,438",NaN,"41,584","2,240"
19,NaN,12.0,Argentina,"2,133,963",NaN,"52,644",NaN,"1,928,377",NaN,"152,942","3,521"
20,NaN,13.0,Mexico,"2,112,508","+7,521","188,866",+822,"1,655,549","+5,319","268,093","4,798"
21,NaN,14.0,Poland,"1,750,659",NaN,"44,649",NaN,"1,448,619",NaN,"257,391","1,650"
22,NaN,15.0,Iran,"1,665,103",NaN,"60,431",NaN,"1,420,958",NaN,"183,714","3,760"
23,NaN,16.0,South Africa,"1,517,666",NaN,"50,462",NaN,"1,436,010",NaN,"31,194",546

In [31]:
df.iloc[7:]

,Unnamed: 0,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical"
7,NaN,NaN,World,"116,216,580","+8,934","2,581,649",+857,"91,884,249","+6,339","21,750,682","89,747"
8,NaN,1.0,USA,"29,526,086",NaN,"533,636",NaN,"20,093,442",NaN,"8,899,008","13,934"
9,NaN,2.0,India,"11,173,572",NaN,"157,584",NaN,"10,838,021",NaN,"177,967","8,944"
10,NaN,3.0,Brazil,"10,796,506",NaN,"261,188",NaN,"9,637,020",NaN,"898,298","8,318"
11,NaN,4.0,Russia,"4,290,135",NaN,"87,823",NaN,"3,869,857",NaN,"332,455","2,300"
12,NaN,5.0,UK,"4,201,358",NaN,"124,025",NaN,"3,096,564",NaN,"980,769","1,647"
13,NaN,6.0,France,"3,835,595",NaN,"87,835",NaN,"262,690",NaN,"3,485,070","3,633"
14,NaN,7.0,Spain,"3,142,358",NaN,"70,501",NaN,"2,722,304",NaN,"349,553","2,615"
15,NaN,8.0,Italy,"2,999,119",NaN,"98,974",NaN,"2,453,706",NaN,"446,439","2,475"
16,NaN,9.0,Turkey,"2,746,158",NaN,"28,839",NaN,"2,601,137",NaN,"116,182","1,220"
17,NaN,10.0,Germany,"2,484,306",NaN,"72,007",NaN,"2,283,400",NaN,"128,899","2,848"
18,NaN,11.0,Colombia,"2,266,211",NaN,"60,189",NaN,"2,164,438",NaN,"41,584","2,240"
19,NaN,12.0,Argentina,"2,133,963",NaN,"52,644",NaN,"1,928,377",NaN,"152,942","3,521"

In [32]:
import plotly.express as px
fig = px.bar(df, x='Country,Other', y='TotalDeaths')
fig.show()